# Bakes the two camp bears into js/sprites/bears.js as char grids.
#
#   python3 app/bake-bears/bake.py     # needs numpy; rerun after changing the rig
#
# The bears are not typed by hand: rig.py paints a bear as shaded ellipse
# parts (bear.py lays them out and poses them, anim.py holds the walk and the
# attack), renders each pose at 8x, shrinks it to the game's pixel and bands
# it into the palette measured off Noah's reference sheet. The black bear is
# the same frames recoloured, wearing its antlers and back runes as exact
# 1x stickers. The grids this writes are the game's only copy.
import os, numpy as np
from rig import draw, PAL, PAL_DARK
from bear import pose
from anim import walk, WALK_N, ATTACK

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(HERE + '/../../js/sprites/bears.js')
BITE = ATTACK[2:]   # the rear-up onward: the bite lands as the clip starts
CH = {'D0': '0', 'D1': '1', 'M3': '3', 'L6': '6', 'H8': '8', 'G7': 'g', 'EY': 'e', 'BN': 'b', 'BS': 's'}

def grid(img, pal):
    inv = {tuple(v): k for k, v in pal.items() if k != 'H8'} | {tuple(pal['H8']): 'H8'}
    rows = []
    for y in range(img.shape[0]):
        r = ''
        for x in range(img.shape[1]):
            if img[y, x, 3] == 0: r += '.'; continue
            c = tuple(int(v) for v in img[y, x, :3])
            name = 'L6' if pal is PAL_DARK and c == pal['L6'] else inv[c]
            r += CH[name]
        rows.append(r)
    return rows

def bear(dark):
    pal = PAL_DARK if dark else PAL
    clips = {
        'idle': [pose(dark=dark)],
        'run': [pose(walk(f), dark=dark) for f in range(WALK_N)],
        'bite': [pose(p, dark=dark) for p in BITE],
    }
    imgs = {k: [draw(p, None, pal)[0] for p in v] for k, v in clips.items()}
    return imgs, pal

sets = {'brown': bear(False), 'black': bear(True)}
# one box for every frame of both bears, so the feet sit on the same row and
# the body on the same column whatever the clip
alls = [f for imgs, _ in sets.values() for fr in imgs.values() for f in fr]
on = np.any([f[..., 3] > 0 for f in alls], axis=0)
ys, xs = np.nonzero(on)
y0, y1, x0, x1 = ys.min(), ys.max() + 1, xs.min(), xs.max() + 1

def js_pal(pal):
    hexc = lambda c: '#%02x%02x%02x' % c
    keys = [k for k in CH if k in pal]
    return '{ ' + ', '.join(f"'{CH[k]}': '{hexc(pal[k])}'" for k in keys) + ", '.': null }"

out = []
out.append("'use strict';")
out.append("// The two midline camps' bears: the BROWN BEAR (the epic camp, SPRITES.dire)")
out.append("// and the BLACK BEAR (the buff camp, SPRITES.alpha). GENERATED by")
out.append("// app/bake-bears/bake.py from a painted 2D rig - edit the rig and rebake,")
out.append("// never these grids. Clips: idle, run (the walk), bite (the rear-up and")
out.append("// swipe). Drawn facing left; right is the mirror.")
out.append("(() => {")
out.append("  const { bakeClips, mapClips, flipH } = SPR;")
for name, (imgs, pal) in sets.items():
    out.append(f"  const {name.upper()}_PAL = {js_pal(pal)};")
    out.append(f"  const {name.upper()} = {{")
    for k, frames in imgs.items():
        out.append(f"    {k}: [")
        for f in frames:
            out.append("      [")
            for r in grid(f[y0:y1, x0:x1], pal):
                out.append(f"        '{r}',")
            out.append("      ],")
        out.append("    ],")
    out.append("  };")
out.append("  const brown = bakeClips(BROWN, BROWN_PAL), black = bakeClips(BLACK, BLACK_PAL);")
out.append("  Object.assign(SPRITES, {")
out.append("    dire: { left: brown, right: mapClips(brown, flipH) },")
out.append("    alpha: { left: black, right: mapClips(black, flipH) },")
out.append("  });")
out.append("})();")
open(OUT, 'w').write('\n'.join(out) + '\n')
print('wrote', OUT, 'frame', x1 - x0, 'x', y1 - y0)
