# Bakes the two camp bears into js/sprites/bears.js as char grids.
#
#   python3 app/bake-bears/bake.py     # needs numpy; rerun after changing the rig
#
# The bears are not typed by hand: rig.py paints a bear as shaded ellipse
# parts (bear.py lays them out and poses them, anim.py holds the walk and the
# attack), renders each pose at 8x, shrinks it to the game's pixel and bands
# it into the palette measured off Noah's reference sheet. The black bear is
# the same frames recoloured, wearing its antlers and back runes as exact
# 1x stickers. The grids this writes are the game's only copy.
import os, numpy as np
from rig import draw, PAL, PAL_DARK
from bear import pose
from anim import CLIPS

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(HERE + '/../../js/sprites/bears.js')
CH = {'D0': '0', 'D1': '1', 'M3': '3', 'L6': '6', 'H8': '8', 'G7': 'g', 'EY': 'e', 'BN': 'b', 'BS': 's', 'SM': 'w', 'SD': 'k', 'FL': 'f', 'FM': 'm'}

def grid(img, pal):
    inv = {tuple(v): k for k, v in pal.items() if k != 'H8'} | {tuple(pal['H8']): 'H8'}
    rows = []
    for y in range(img.shape[0]):
        r = ''
        for x in range(img.shape[1]):
            if img[y, x, 3] == 0: r += '.'; continue
            c = tuple(int(v) for v in img[y, x, :3])
            name = 'L6' if pal is PAL_DARK and c == pal['L6'] else inv[c]
            r += CH[name]
        rows.append(r)
    return rows

def bear(dark):
    pal = PAL_DARK if dark else PAL
    imgs = {k: [draw(pose(p, dark=dark), None, pal)[0] for p in v] for k, v in CLIPS.items()}
    return imgs, pal

sets = {'brown': bear(False), 'black': bear(True)}
# one box for every frame of both bears, so the feet sit on the same row and
# the body on the same column whatever the clip
alls = [f for imgs, _ in sets.values() for fr in imgs.values() for f in fr]
on = np.any([f[..., 3] > 0 for f in alls], axis=0)
ys, xs = np.nonzero(on)
y0, y1, x0, x1 = ys.min(), ys.max() + 1, xs.min(), xs.max() + 1
# the game centres a frame on the animal, so centre the box on the standing
# bear's own middle, not on everything the attacks and the rear-up reach
iy, ix = np.nonzero(sets['brown'][0]['idle'][0][..., 3] > 0)
mid = (ix.min() + ix.max() + 1) / 2
half = int(np.ceil(max(mid - x0, x1 - mid)))
x0, x1 = int(mid - half), int(mid + half)
# rows above the standing bear's head: the tells hang off the head, not the box
TOP = int(iy.min() - y0)
# rows above each bear's tallest pose (the rear-up, a new clip's leap): its
# frame sits over that, so no clip ever climbs into its bars
def crown(imgs):
    return int(np.nonzero(np.any([f[..., 3] > 0 for fr in imgs.values() for f in fr], axis=(0, 2)))[0].min() - y0)
CROWN = {name: crown(imgs) for name, (imgs, _) in sets.items()}

def js_pal(pal):
    hexc = lambda c: '#%02x%02x%02x' % c
    keys = [k for k in CH if k in pal]
    return '{ ' + ', '.join(f"'{CH[k]}': '{hexc(pal[k])}'" for k in keys) + ", '.': null }"

out = []
out.append("'use strict';")
out.append("// The two midline camps' bears: the BROWN BEAR (the epic camp, SPRITES.dire)")
out.append("// and the BLACK BEAR (the buff camp, SPRITES.alpha). GENERATED by")
out.append("// app/bake-bears/bake.py from a painted 2D rig - edit the rig and rebake,")
out.append("// never these grids. Clips: idle, walk, run (the gallop), bite (the lunge),")
out.append("// paw (the side swipe, with its claw trail), roar (the one rear-up) and fish (the river")
out.append("// catch: scoop, snap, chew). Drawn facing left;")
out.append("// right is the mirror.")
out.append("(() => {")
out.append("  const { bakeClips, mapClips, flipH } = SPR;")
for name, (imgs, pal) in sets.items():
    out.append(f"  const {name.upper()}_PAL = {js_pal(pal)};")
    out.append(f"  const {name.upper()} = {{")
    for k, frames in imgs.items():
        out.append(f"    {k}: [")
        for f in frames:
            out.append("      [")
            for r in grid(f[y0:y1, x0:x1], pal):
                out.append(f"        '{r}',")
            out.append("      ],")
        out.append("    ],")
    out.append("  };")
out.append("  // `top`: the empty rows over the standing bear's head, so drawAnimal hangs")
out.append("  // the tells off the bear rather than off the headroom the rear-up needs;")
out.append("  // `crown`: the empty rows over this bear's tallest pose in any clip, where")
out.append("  // its frame sits so no rear-up or lunge climbs into the bars")
out.append(f"  const TOP = {TOP};")
out.append("  const set = (grids, pal, crown) => {")
out.append("    const left = bakeClips(grids, pal), right = mapClips(left, flipH);")
out.append("    for (const s of [left, right]) for (const k in s) for (const c of s[k]) { c.top = TOP; c.crown = crown; }")
out.append("    return { left, right };")
out.append("  };")
out.append(f"  Object.assign(SPRITES, {{ dire: set(BROWN, BROWN_PAL, {CROWN['brown']}), alpha: set(BLACK, BLACK_PAL, {CROWN['black']}) }});")
out.append("})();")
open(OUT, 'w').write('\n'.join(out) + '\n')
print('wrote', OUT, 'frame', x1 - x0, 'x', y1 - y0)
