'use strict';
// Everything with four legs or wings: the imp, the rabbit, the deer, the wolf,
// the bird, and the camps' alpha and dire wolf derived from the wolf.
(() => {
  const { bake, flipH, bakeClips, mapClips, wash, double } = SPR;

  // ---------------------------------------------------------------- imp
  const IPAL = {
    '.': null,
    'o': '#141f3d', // outline
    'i': '#5f8fc0', // ice body mid
    'I': '#8fc2dd', // ice light (top)
    'j': '#41628f', // ice shade
    'e': '#101a33', // eye socket
    'E': '#54f0e6', // eye glow
    'h': '#c6ecf4', // horn
    'H': '#8fc2dd', // horn shade
  };

  const imp1 = [
    '..............',
    '...oo....oo...',
    '..ohho..ohho..',
    '..oHho..oHho..',
    '...oiIIIIio...',
    '..oiIIIIIIio..',
    '.oiIeeIIeeIio.',
    '.oiIeEIIeEIio.',
    '.oiIIIIIIIijo.',
    '.oijIIooIIjjo.',
    '..oijjjjjjjo..',
    '...oooooooo...',
    '..ojjo..ojjo..',
    '...oo....oo...',
  ];
  const imp2 = [
    '..............',
    '..............',
    '...oo....oo...',
    '..ohho..ohho..',
    '..oHhooooHho..',
    '..oiIIIIIIio..',
    '.oiIeeIIeeIio.',
    '.oiIeEIIeEIio.',
    '.oiIIIIIIIijo.',
    '.oijIIooIIjjo.',
    '..oijjjjjjjo..',
    '.ojjoooooojjo.',
    '..oo......oo..',
    '..............',
  ];

  // ---------------------------------------------------------------- rabbit
  // The meadow's bunny, side view facing right: a chunky brown hare with a
  // pink inner ear and one white glint in the eye. Three sheets out of
  // docs/media/new_media3/ split at 32 px into the three CLIPS a behaviour
  // plays (ANIM_CLIPS, js/wildlife.js): `idle` is
  // bunny_facing_right_gently_look_around, `hop` is
  // bunny_facing_right_hopping_right, `rise` is
  // bunny_facing_right_stand_up_and_wiggle - the sit-up a rabbit that has
  // noticed you does. The source order IS the animation order in all three.
  //
  // The sheets are drawn far bigger than the meadow wants them - at its own
  // cell size this bunny stands taller than a 16 px player - so the offline
  // pass that made these grids RESAMPLED each frame down to the 11x12 they
  // ship at, snapping every pixel onto RBPAL and every edge to hard alpha.
  // What is written here is therefore what draws: bake() paints it 1:1, and
  // editing a character here changes exactly one pixel in the game. (Baking
  // the big grid and halving it at load - an alpha-weighted 2x2 average, which
  // this file used to do for the gold sack - leaves every edge a soft fringe
  // and invents colours the palette never had: pixel art with the pixels
  // sanded off. Snapping offline keeps both hard.)
  //
  // All three clips share ONE crop of the source, the box every frame of
  // every clip fits inside, or a clip taking over would jump against the one
  // it replaced.
  const RBPAL = {
    '.': null,
    'o': '#040102', // outline
    'e': '#22110a', // eye, and the deepest shadow
    'D': '#371c0f', // fur, deepest
    'd': '#512c1c', // fur, dark
    's': '#73472d', // fur, shade
    'S': '#88593a', // fur, shade light
    'f': '#9a6a45', // fur
    'F': '#b27f57', // fur, light
    'h': '#c29068', // fur, highlight
    'p': '#c9897f', // inner ear
    'w': '#d0c8be', // eye glint
  };

  const rabbitIdle = [
    [
      '...........',
      '....eDDd...',
      '....sSds...',
      '....dFssd..',
      '.....dSfFs.',
      '.....sfSfS.',
      '...ddSfsffD',
      '..dffSSfSs.',
      '.eSfSfSSSD.',
      'DdffSffhhd.',
      '.eSfssfSd..',
      '..DddDdDD..',
    ],
    [
      '...........',
      '.....d.d...',
      '....sfDsD..',
      '....DFsss..',
      '.....dfFFs.',
      '.....sSffS.',
      '...ddSfSfsD',
      '..dffsSfsS.',
      '.eSfSfSSSD.',
      'DdffSffhhd.',
      '.eSfssfSd..',
      '..DddDdDD..',
    ],
    [
      '...........',
      '.....s.DD..',
      '.....SDdd..',
      '.....Ssss..',
      '.....sfFfD.',
      '.....SSffs.',
      '...ddfsffs.',
      '..dfSsffsd.',
      '.eSfSfSSSD.',
      'DdffSffhhd.',
      '.eSfssfSd..',
      '..DddDdDD..',
    ],
    [
      '...........',
      '.....s..d..',
      '.....Sdds..',
      '.....ssss..',
      '.....sfFfD.',
      '.....SSffd.',
      '...dsfSfSs.',
      '..dffsfSSd.',
      '.effSfSffd.',
      'DdffSfFhhd.',
      '.DSfssffd..',
      '..DddDdDD..',
    ],
    [
      '...........',
      '.....dD.D..',
      '.....SDdd..',
      '.....Ssss..',
      '.....sfFfD.',
      '.....SSffd.',
      '...dsfSfSs.',
      '..dffsfSSd.',
      '.eSfSfSffd.',
      'DdffSfFhhd.',
      '.eSfssffd..',
      '..DddDdDD..',
    ],
    [
      '...........',
      '.....dD.D..',
      '.....SdDs..',
      '.....Ssss..',
      '.....sfFfD.',
      '.....SSffd.',
      '...dsfSffs.',
      '..dffSfSSd.',
      '.DffSfSffd.',
      '.dffSfFhhd.',
      '.eSfssffd..',
      '..DddDdDD..',
    ],
    [
      '...........',
      '.....s.DD..',
      '.....Sedd..',
      '.....Sdsd..',
      '.....sfFfD.',
      '.....SSffd.',
      '...ddfSffs.',
      '..dfSsffsd.',
      '.offSfSSSd.',
      'DdffSffhhd.',
      '.dSfssffd..',
      '..DddDdDD..',
    ],
    [
      '...........',
      '.....d.dD..',
      '....dSDsd..',
      '.....Ssss..',
      '.....dffFs.',
      '.....sSffS.',
      '...ddSfSfSD',
      '..dffsSfsS.',
      '.eSfSfSSSD.',
      'DdffSffhhd.',
      '.eSfssfSd..',
      '..DddDdDD..',
    ],
    [
      '...........',
      '....eDDd...',
      '....sSdsD..',
      '....dFssd..',
      '.....dSfFs.',
      '.....sfsfS.',
      '...ddSfsffD',
      '..dffsSfSs.',
      '.eSfSfSSSD.',
      'DdffSffhhd.',
      '.eSfssfSd..',
      '..DddDdDD..',
    ],
    [
      '...........',
      '....eDDd...',
      '....sSds...',
      '....dFssd..',
      '.....dSfFs.',
      '.....sfSfS.',
      '...ddSfsffD',
      '..dffsSfSs.',
      '.eSfSfSSSD.',
      'DdffSffhhd.',
      '.eSfssfSd..',
      '..DddDdDD..',
    ]
  ];

  const rabbitHop = [
    [
      '...........',
      '....eDDd...',
      '....dSds...',
      '....DFssd..',
      '.....dSfFs.',
      '.....sfSfS.',
      '...ddSfsffD',
      '..dffSSfSs.',
      '.eSfSfSSSD.',
      'DsffSffhhd.',
      '.eSfsSfSs..',
      '..DddDdDD..',
    ],
    [
      '...........',
      '...........',
      '....dsDd...',
      '....dFssD..',
      '.....FsSs..',
      '.....dffFs.',
      '...ddsfsfS.',
      '..dfSSfSfSD',
      '.eSfSSSSSd.',
      'DdffSffffd.',
      '.eSfsSsFf..',
      '..DddddDD..',
    ],
    [
      '...........',
      '...........',
      '....DDdD...',
      '....SSdde..',
      '.....SSfFd.',
      '.....dfSfS.',
      '..DsSSfsfS.',
      '..sffSfffSD',
      'DsffffSSsd.',
      '.dffSffFhd.',
      '.ofssssss..',
      '..ddeDee...',
    ],
    [
      '.....e.....',
      '....sddd...',
      '....ffsSs..',
      '.....sffFs.',
      '.....sfsfS.',
      '...ssSfSfSD',
      '.esffSSSSd.',
      'DdffffSSfd.',
      '.dffffSfSd.',
      '.SfSfhfeoD.',
      '.SDDsdD....',
      '.d.eD......',
    ],
    [
      '...........',
      '....dddd...',
      '....sSssD..',
      '.....sSfFd.',
      '....DdfSfS.',
      '..dSSSfsffD',
      'DsSffsSffsD',
      '.dffffSSsD.',
      '.sffSfffhs.',
      'dSsdssdsfse',
      'd..D....Dd.',
      '...........',
    ],
    [
      '...........',
      '...........',
      '....DDDD...',
      '....sSds...',
      '.....FsSs..',
      '.....dffFs.',
      '..DsSsfsfS.',
      '.DSfsSfSfSD',
      'DdffSsSSSd.',
      '.DffSffffd.',
      '..sdsSfFfD.',
      '.....eDdDD.',
    ]
  ];

  const rabbitRise = [
    [
      '...........',
      '....eDDd...',
      '....dSds...',
      '....dFssd..',
      '.....dSfFs.',
      '.....sfSfS.',
      '...ddSfsffD',
      '..dffsSfSs.',
      '.eSfSfSSSD.',
      'DdffSffhhd.',
      '.eSfssfSs..',
      '..DddDdDD..',
    ],
    [
      '...........',
      '....dDdD...',
      '....SSdd...',
      '....dfSSSD.',
      '.....dfffS.',
      '.....sfdfS.',
      '...dsSfffSD',
      '..dffSsSsd.',
      '.oSffffFFd.',
      '.dffSffSSd.',
      '.dsfsfsdeD.',
      '..DddD.....',
    ],
    [
      '.....e.....',
      '....SssD...',
      '....fSsss..',
      '.....sffFs.',
      '.....sfsfS.',
      '....dSfSfSD',
      '...dfSSSSd.',
      '..dfffSffD.',
      '.oSfffSSSd.',
      'DdffSFFd...',
      '.dsfsfs....',
      '..DddD.....',
    ],
    [
      '...........',
      '...dsDdD...',
      '....FSsss..',
      '.....dffFs.',
      '.....sfsfS.',
      '....dSfSfSD',
      '..DsfSSSSd.',
      '..sfffSSfde',
      '.DffffSsSD.',
      'DdffSFhs...',
      '.esfsfs....',
      '...dde.....',
    ],
    [
      '...........',
      '....sdd....',
      '....SSddD..',
      '....dSSfFd.',
      '.....dfSfS.',
      '...DdSfsffD',
      '..sffSSffsD',
      '.effffSSsD.',
      'DdffSffFhd.',
      '.eSfSfSfdD.',
      '..dSse.e...',
      '...DD......',
    ],
    [
      '...........',
      '...........',
      '.....Sdd...',
      '.....Fsde..',
      '.....sSfFs.',
      '....dDSSffD',
      '..sffsfsffd',
      'DdfffSSffSd',
      'ddffSfSsSd.',
      '.DffSffFFD.',
      '..dssdSfS..',
      '.......dDe.',
    ],
    [
      '...........',
      '...........',
      '....DdDD...',
      '....dfdde..',
      '.....fSfFs.',
      '.....eSSffD',
      '..Dsfsfsffd',
      '..sffSfffSd',
      'DsffffSsSd.',
      '.dfffffFhd.',
      '..sfsSfffD.',
      '...DdDDdDe.',
    ],
    [
      '...........',
      '.....DDd...',
      '....dSds...',
      '....dFssd..',
      '.....dSfFs.',
      '.....sfSfS.',
      '...ddSfsffD',
      '..dffsSfSs.',
      '.eSfSffSSD.',
      'DdffSffhhd.',
      '.eSfssfSs..',
      '..DddDdDD..',
    ]
  ];

  // ---------------------------------------------------------------- deer
  // The stag, side view facing right: warm coat, pale antlers, dark slender
  // legs. Three sheets out of docs/media/new_media3/ split at 38 px into the
  // clips (ANIM_CLIPS, js/wildlife.js): `idle` is
  // deer_facing_right_gently_look_around (head up, watching), `graze` is
  // deer_facing_right_grazing_loop (head down into the snow and back) and
  // `run` is deer_facing_right_galloping. Head up against head down is the
  // whole read on whether it has seen you, which is why the two idles are
  // separate clips rather than one longer loop.
  //
  // Resampled to the 19x19 it ships at and snapped onto DEPAL, the same pass
  // and for the same reason as the rabbit above.
  const DEPAL = {
    '.': null,
    'o': '#040202', // outline
    'e': '#27140b', // eye and hoof, deepest
    'D': '#442514', // coat, deepest
    'd': '#5e361f', // coat, dark
    'v': '#6f4224', // coat, shade
    'n': '#6f5136', // antler, deep
    'b': '#8f582f', // coat
    'a': '#7f6446', // antler
    'B': '#9d6639', // coat, light
    'c': '#9b744f', // antler, warm
    'L': '#b47844', // coat, lit
    'A': '#b48a60', // antler, light
    'C': '#b7986d', // antler, lit
  };

  const deerIdle = [
    [
      '......oo.e..e.e....',
      '......nnD....DDo...',
      '.......nDonoDoD.o..',
      '........nndodoDdo..',
      '.........ednDDDD...',
      '..........nnvbe....',
      '...........eBbBo...',
      '..........oddvdD...',
      '.........oDvLao....',
      '....edddvBvbbAd....',
      '...DLBBLBbdnvbD....',
      '..evbbbbbbbDvvo....',
      '..ovbvbbdbBdde.....',
      '...ebDDvdvBDeo.....',
      '...DDeeooDdoe......',
      '..eDoe...eDoe......',
      '..Do.o...oeoe......',
      '..Do.eo..oDoe......',
      '..oo.oo..oooo......',
    ],
    [
      '......oo.e..oDoD...',
      '......nnD....eeD...',
      '.......aDone.odoo..',
      '........nnddooDdo..',
      '.........ednDdDD...',
      '.........DcDvbe....',
      '..........ovaLdo...',
      '..........odvdv....',
      '.........oDvBao....',
      '....edddvBvbbAd....',
      '...DLBBLBbdnvbD....',
      '..evbbbbbbbDvvo....',
      '..ovbvbbdbBdde.....',
      '...ebDDvdvBDeo.....',
      '...DDeeooDdoe......',
      '..eDoe...eDoe......',
      '..Do.o...oeoe......',
      '..Do.eo..oDoe......',
      '..oo.oo..oooo......',
    ],
    [
      '......oD.e..oeoe...',
      '......dnDo...eeD...',
      '.......nDnoD.DDoo..',
      '........naDn.DDD...',
      '.........edaodDo...',
      '.........DBDbvo....',
      '..........obnBo....',
      '..........ovvdD....',
      '.........oDbano....',
      '....edddvBvvALe....',
      '...DLBBLBbdvvbe....',
      '..evbbbbbbbDddo....',
      '..ovbvbbdbBDde.....',
      '...ebDDvdbvDeo.....',
      '...DDeeooveoe......',
      '..eDoe...eDoe......',
      '..Do.o...oeoe......',
      '..Do.eo..oDoe......',
      '..oo.oo..oooo......',
    ],
    [
      '.......doe...e.e...',
      '......ocDo....Ddo..',
      '.......dDnoD.DoDo..',
      '........naed.DDD...',
      '.........edaodDo...',
      '.........DBDvve....',
      '..........obano....',
      '..........ovvdD....',
      '.........oDnano....',
      '....edddvBvvALe....',
      '...DLBBLBbdvvbe....',
      '..evbbbbbBBDddo....',
      '..ovbvbbvbBdde.....',
      '...ebDDvvbbDeo.....',
      '...DDeeoebooe......',
      '..eDoe...eeoe......',
      '..Do.o...oDoe......',
      '..Do.eo..oDoe......',
      '..oo.oo..oooo......',
    ],
    [
      '.......doe...e.e...',
      '......ocDo....Ddo..',
      '.......dDnoD.DoDo..',
      '........naed.DDd...',
      '.........edaodDo...',
      '.........DBDvve....',
      '..........obano....',
      '..........ovvdD....',
      '.........oDnano....',
      '....edddvBvvALe....',
      '...DLBBLBbdvvbe....',
      '..evbbbbbbbDdDo....',
      '..ovbvbbdbBdde.....',
      '...ebDDvdbbDeo.....',
      '...DDeeoeveoe......',
      '..eDoe...Deoe......',
      '..Do.o...oDoe......',
      '..Do.eo..oDoe......',
      '..oo.oo..oooo......',
    ],
    [
      '.......doe...e.e...',
      '......ocDo....Ddo..',
      '.......dDnoD.DoDo..',
      '........naed.DDd...',
      '.........edaodD....',
      '.........DdDbvo....',
      '..........ebano....',
      '..........ovvdD....',
      '.........oDnano....',
      '....edddvBvvALe....',
      '...DLBBLBbdvvbe....',
      '..evbbbbbbbDdDo....',
      '..ovbvbbdbBdde.....',
      '...ebDDvdvBDeo.....',
      '...DDeeooDdoe......',
      '..eDoe...eDoe......',
      '..Do.o...oeoe......',
      '..Do.eo..oDoe......',
      '..oo.oo..oooo......',
    ],
    [
      '.......doe...e.e...',
      '......ocDo....De...',
      '.......dDnoD.DoDo..',
      '........naed.DDD...',
      '.........edaodD....',
      '.........Dvdvve....',
      '..........obbBe....',
      '..........odvdv....',
      '.........oDnano....',
      '....edddvBvvALe....',
      '...DLBBLBbdvvbe....',
      '..evbbbbbbbDdDo....',
      '..ovbvbbdbBdde.....',
      '...ebDDvdvBDeo.....',
      '...DDeeooDdoe......',
      '..eDoe...eDoe......',
      '..Do.o...oeoe......',
      '..Do.eo..oDoe......',
      '..oo.oo..oooo......',
    ],
    [
      '......oo.e..e.e....',
      '......nnD....DDo...',
      '.......nDonoDoD.o..',
      '........nndodoDdo..',
      '.........enaDDDD...',
      '..........nnvbe....',
      '...........eBBBo...',
      '..........odvvdD...',
      '.........oDvLao....',
      '....edddvBvbBAd....',
      '...DLBBLBbdnnbD....',
      '..evbbbbbbBDvvo....',
      '..ovbvbbdbBdde.....',
      '...ebDDddvBDeo.....',
      '...DDeeooDdoe......',
      '..eDoe...eDoe......',
      '..Do.o...oeoe......',
      '..Do.eo..oDoe......',
      '..oo.oo..oooo......',
    ],
    [
      '......oo.e..e.e....',
      '......nnD....DDo...',
      '.......nDonoDoD.o..',
      '........nndodoDdo..',
      '.........edaDDDD...',
      '..........bnvbe....',
      '...........eBbBo...',
      '..........odvvdD...',
      '.........oDvLao....',
      '....edddvBvbbAd....',
      '...DLBBLBbdnvbD....',
      '..evbbbbbbBDvvo....',
      '..ovbvbbdbBdde.....',
      '...ebDDvdvBDeo.....',
      '...DDeeooDdoe......',
      '..eDoe...eDoe......',
      '..Do.o...oeoe......',
      '..Do.eo..oDoe......',
      '..oo.oo..oooo......',
    ],
    [
      '......oo.e..e.e....',
      '......nnD....DDo...',
      '.......nDonoDoD.o..',
      '........nndodoDdo..',
      '.........edaDDDD...',
      '..........nnvbe....',
      '...........eBbBo...',
      '..........oddvdD...',
      '.........oDvLao....',
      '....edddvBvbbAd....',
      '...DLBBLBbdnvbD....',
      '..evbbbbbbBDvvo....',
      '..ovbvbbdbBdde.....',
      '...ebDDvdvBDeo.....',
      '...DDeeooDdoe......',
      '..eDoe...eDoe......',
      '..Do.o...oeoe......',
      '..Do.eo..oDoe......',
      '..oo.oo..oooo......',
    ]
  ];

  const deerGraze = [
    [
      '......oo.D..e.e....',
      '......nnD....DDo...',
      '.......aDonoDoD.o..',
      '........nndonoDdo..',
      '.........ednDDDe...',
      '..........nnvbe....',
      '...........eBbBo...',
      '..........odvvdD...',
      '.........oDvLbo....',
      '....edddvBvbbAd....',
      '...dLBBLBbdvvbD....',
      '..evbbbbbbBDvvo....',
      '..ovbvbbdbBdde.....',
      '...ebDDddvbDeo.....',
      '...DDeeooDdoe......',
      '..eDoe...eDoe......',
      '..Do.o...oeoe......',
      '..Do.eo..oDoe......',
      '..oo.oo..oeoo......',
    ],
    [
      '...................',
      '.......Do.D.oeoe...',
      '.......DaD...eeD...',
      '........DDonoDDe.o.',
      '.........dndovoDno.',
      '..........ednDDDD..',
      '...........bnvbe...',
      '...........eDBabo..',
      '.........oeddvddo..',
      '....edddvBdbBcD....',
      '...dLBBLBbvbvLd....',
      '..evbbbbbbbdvvD....',
      '..ovbvbbdbBdvDo....',
      '...ebDDddvbDee.....',
      '...DDeeooDdoe......',
      '..eDoe...eDoe......',
      '..Do.o...oeoe......',
      '..Do.eo..oDoe......',
      '..oo.oo..oe.o......',
    ],
    [
      '...................',
      '...................',
      '.........o.........',
      '.........dodo.o.e..',
      '..........ae...DDo.',
      '..........DadoDoD..',
      '...........nnDnoDeo',
      '............DnDenn.',
      '.........o.oobddo..',
      '....edddvLvdddnne..',
      '...dLBBLBbvbbvbBco.',
      '..evbbbbbbdbbBDodD.',
      '..ovbvbbvbvvbLD....',
      '...ebDDddbvdvd.....',
      '...DDeeoovDeo......',
      '..eDoe...DDee......',
      '..Do.o...oe.eo.....',
      '..Do.eo..oDoe......',
      '..oo.oo..oe.e......',
    ],
    [
      '...................',
      '...................',
      '...................',
      '...................',
      '...................',
      '.............n.....',
      '............doo.o..',
      '............dde.eoo',
      '............ed..eD.',
      '.....ooooddoon..ovo',
      '...oDLLBLBBvDne.DDD',
      '..edbBbBBbvbvbndDD.',
      '...ebbbbbBvbbvbdDo.',
      '...ebbDvvbDbBvbdD..',
      '...DveeDDbddBvnvD..',
      '..eDeee..evoeoeBdo.',
      '..Do.o....Doeo.eD..',
      '..Do.eo..odoe......',
      '..oo.oo...eoo......',
    ],
    [
      '...................',
      '...................',
      '...................',
      '...................',
      '...................',
      '...................',
      '...................',
      '..............D....',
      '.............no.oo.',
      '.....ooooDd..dnooDe',
      '....DLLBLLLvede..Do',
      '..edbBbBBbbvvvo..Do',
      '...ebbbbbbvbbdD.ede',
      '...ebbdvvBvbbecddee',
      '...evDedvbDvvBvveo.',
      '..edeeeooebdbvBbo..',
      '..Deoe....DeeDnbo..',
      '..Do.eo..odoeovBo..',
      '..oo.oo...eoo..D...',
    ],
    [
      '...................',
      '...................',
      '...................',
      '...................',
      '...................',
      '...................',
      '...................',
      '...................',
      '..............d..o.',
      '.....ooooDd..eaooDe',
      '...oDLLBLBLvedn..eD',
      '..edbBbBBbbvvvo..Do',
      '...ebbbbbBbbbdD..Do',
      '...ebbdvvBvbvenodoD',
      '...evDedvbDbbBnvdo.',
      '..edeeeooebdbdbbo..',
      '..Deoe....Deovabo..',
      '..Do.eo..odoeebBo..',
      '..oo.oo...eoo.DDo..',
    ],
    [
      '...................',
      '...................',
      '...................',
      '...................',
      '...................',
      '...................',
      '...................',
      '.............DD..o.',
      '.............ddooee',
      '.....oooeddo.do..ee',
      '...oDLLBLBBvevo..Do',
      '..edbBbBBbbvvno.ono',
      '...ebbbbbbbbvdnoDeD',
      '...ebbdvvBdbvBndDe.',
      '...evDeDdbdbbvbbe..',
      '..edeee..ebDDvabo..',
      '..Deoe....DeoebBo..',
      '..Do.eo..odoe.DDo..',
      '..oo.oo...eoo......',
    ],
    [
      '...................',
      '...................',
      '...................',
      '...................',
      '..........e.Do.o.o.',
      '..........DnD..eee.',
      '...........noD..DDo',
      '...........DDDonoDo',
      '.........o..DvdDoDd',
      '....eddDdBnDeddDDDo',
      '..odLLBLLbbvvdbnd..',
      '..evbbbbbbvbbvvbLd.',
      '..ovbbbbbBvbbLvdnn.',
      '...ebDdvvBDdbce.o..',
      '...DdeeDebDDDD.....',
      '..eDoDe..edoe......',
      '..Do.o....D.eo.....',
      '..Do.eo..oDoe......',
      '..oo.oo..oeoo......',
    ],
    [
      '...................',
      '...................',
      '........o.Do.oeoD..',
      '.......onnD...een..',
      '........econoD.Doo.',
      '.........eadDnoDed.',
      '..........ondnodD..',
      '...........DBvvv...',
      '.........oooevnLdo.',
      '....edddvLvdvdvnv..',
      '...dLBBLBbvbbLdo...',
      '..evbbbbbbvbbAd....',
      '..ovbvbbbBvdvnD....',
      '...ebDDddbvdde.....',
      '...DDeeoeveeo......',
      '..eDoe...DDee......',
      '..Do.o...oeoe......',
      '..Do.eo..oDoe......',
      '..oo.oo..oeoo......',
    ],
    [
      '..........o.o......',
      '......oDDn...DoD...',
      '.......dnoD.o.De...',
      '........nDdonoDoe..',
      '.........dandonde..',
      '..........oDnDDo...',
      '...........dbdBe...',
      '...........ovBBao..',
      '.........oedvneo...',
      '....edddvBdvcLd....',
      '...dLBBLBbvbvcd....',
      '..evbbbbbbbdnbe....',
      '..ovbvbbdbBDdD.....',
      '...ebDDddvbDe......',
      '...DDeeooDDee......',
      '..eDoe...eDoe......',
      '..Do.o...oeoe......',
      '..Do.eo..oDoe......',
      '..oo.oo..oeoo......',
    ],
    [
      '......oo.D..e.e....',
      '......nnD....DDo...',
      '.......aDonoDoD.o..',
      '........nndonoDvo..',
      '.........ednDDDe...',
      '.........onnvbe....',
      '...........eBaBo...',
      '..........odvvdD...',
      '.........oDvLbo....',
      '....edddvBvbbAd....',
      '...dLBBLBbdvvbD....',
      '..evbbbbbbBDvvo....',
      '..ovbvbbdbBdde.....',
      '...ebDDddvbDeo.....',
      '...DDeeooDdoe......',
      '..eDoe...eDoe......',
      '..Do.o...oeoe......',
      '..Do.eo..oDoe......',
      '..oo.oo..oeoo......',
    ],
    [
      '......oo.D..e.e....',
      '......nnD....DDo...',
      '.......aDonoDoD.o..',
      '........nndonoDvo..',
      '.........ednDDDe...',
      '..........nnvbe....',
      '...........eBaBo...',
      '..........odvvdD...',
      '.........oDvLbo....',
      '....edddvBvbbAd....',
      '...dLBBLBbdvvbD....',
      '..evbbbbbbBDvvo....',
      '..ovbvbbdbBdde.....',
      '...ebDDddvbDeo.....',
      '...DDeeooDdoe......',
      '..eDoe...eDoe......',
      '..Do.o...oeoe......',
      '..Do.eo..oDoe......',
      '..oo.oo..oeoo......',
    ]
  ];

  const deerRun = [
    [
      '......oo.D..e.e....',
      '......nnD....DDo...',
      '.......nDonoDoD.o..',
      '........nndonoDdo..',
      '.........ednDDDe...',
      '..........nvvbe....',
      '...........eBbBo...',
      '..........odvvdD...',
      '.........oDvLbo....',
      '....edddvBvbbAd....',
      '...dLBBLBbdvvbD....',
      '..evbbbbbbBDvvo....',
      '..ovbvbbdbbdve.....',
      '...ebDDddvbDeo.....',
      '...DDeeooDdoD......',
      '..eDoe...eDoe......',
      '..Do.o...oDoe......',
      '..Do.eo..odoe......',
      '..oo.oo..oeoo......',
    ],
    [
      '......oo.D..eDe....',
      '......DnD....DDo...',
      '.......nDonoaoDDo..',
      '........dndonend...',
      '.........ednddoe...',
      '..........bbnnd....',
      '...........DbBLD...',
      '..........evbdo....',
      '........ooDvLAo....',
      '....eddnBBvbbAd....',
      '...dLBBLBbdvvbD....',
      '..evbbbbbbBdvvo....',
      '..ovbvbbdbBdve.....',
      '..ovbeeDDvveDe.....',
      '..Ddee..obe.oee....',
      '.oDoe...oD...oe....',
      '.oDoe...oD...oo....',
      '.oe.e...Do...o.....',
      '....oo..o..........',
    ],
    [
      '......DDDD..eeDo...',
      '......Dae.D..eD....',
      '.......eaodonoDeo..',
      '........eaadDend...',
      '.........odDndo....',
      '..........evnnvo...',
      '...........DbBBe...',
      '..........evbdo....',
      '.....oooeddvLcD....',
      '...ebLBLBBdbvcd....',
      '..evBbBBbbvdvve....',
      '..ovbbbbvbBDvD.....',
      '...ebddvdbbDDo.....',
      '..evvDeDDbeeoee....',
      '.oDeee..DD....eo...',
      '.Deee...De....oe...',
      '.e.eo..DD.....oo...',
      '.o.oo.oe...........',
      '...o...............',
    ],
    [
      '......oo.D..e.e....',
      '......nnD....DDo...',
      '.......nDonoDoD.o..',
      '........nndonoDdo..',
      '.........ednDDDe...',
      '..........bnvbe....',
      '...........eBbBo...',
      '..........odvvdD...',
      '.....oo..oDvLbo....',
      '...ebLBdnBvbbAd....',
      '..evBbBLBbdvvbD....',
      '..oDbbbbvBBDvvo....',
      '...evbdvdbbDde.....',
      '..eDvdDddbDDeo.....',
      '..Doooooedo.oee....',
      '.oo.oe..eD....ee...',
      '....oooDD......eo..',
      '......oo........o..',
      '...................',
    ],
    [
      '.........o..o.o....',
      '......DDDD..eeDo...',
      '......Dae.D..eD....',
      '.......eaodonoDeo..',
      '........eaadDend...',
      '..........BDndo....',
      '..........evbnvo...',
      '...........DbBBe...',
      '..........evbdo....',
      '....edooeddvLAD....',
      '...DLBBLBBdbvcd....',
      '..evbbvBbbvdbve....',
      '...DbbdbbBBDvD.....',
      '....DbdvdbbDDe.....',
      '...odeeDevdeeo.....',
      '....DDe..DDoe......',
      '.....eooode.e......',
      '......ooDo..oe.....',
      '.............oo....',
    ],
    [
      '.........o..o.o....',
      '......DDDD..eeDo...',
      '......Dae.D..eD....',
      '.......eaodonoDeo..',
      '........eaadDend...',
      '.........odDndo....',
      '..........evbnvo...',
      '...........DbBBe...',
      '..........evbdo....',
      '.....oooeddvLAD....',
      '...ebLBLBBdbvcd....',
      '..evBbBBbbvdbve....',
      '...DbbvbbbBDvD.....',
      '....DbdvDbbdDe.....',
      '....DeeDDDbDe......',
      '....Doee..edo......',
      '....oD.ee.oDo......',
      '.....Do.eoeeo......',
      '......o..o.oo......',
    ],
    [
      '.........o..o.o....',
      '......DDDD..eeDo...',
      '......Dae.D..eD....',
      '.......eaodonoDeo..',
      '........eaadDend...',
      '.........odDnvo....',
      '..........evnnvo...',
      '...........DbBBe...',
      '..........evbdo....',
      '.....oooDddbLAD....',
      '...ebLBLBBdbvcd....',
      '..evBbBBbbvdbve....',
      '..ovbbbbbbBvve.....',
      '...ebvdvddbvDe.....',
      '...odDeDDedvv......',
      '...eDee...ooDD.....',
      '...eeee...Ded......',
      '...od.e...eo.......',
      '...oo.oo..oo.......',
    ],
    [
      '......oo.D..e.e....',
      '......nnD....DDo...',
      '.......nDonoDoD.o..',
      '........nndonoDdo..',
      '.........ednDDDe...',
      '..........bnvbe....',
      '...........eBbBo...',
      '..........odvvdD...',
      '.........oDvLbo....',
      '....edddnBvbbAd....',
      '...dLBBLBbdvvbD....',
      '..evbbbbbbBdvvo....',
      '..ovbvbbvdbbde.....',
      '..ovbeDddddvbD.....',
      '..DDeeoooooooDo....',
      '.oDoD.....e..oD....',
      '.oDeo....ee..oo....',
      '.ee.Do..oe.........',
      '.o..oo.............',
    ],
    [
      '......oo.D..e.e....',
      '......nnD....DDo...',
      '.......nDonoDoDdo..',
      '........nndonoDDo..',
      '.........ednnDDe...',
      '..........bBvbDo...',
      '..........oDBbBo...',
      '..........evvvdo...',
      '........eddvLbo....',
      '...ebLBBBBdbvcd....',
      '..evBbBBbbvvvbe....',
      '..ovbbbbbbbndD.....',
      '..ovbddvddbbbe.....',
      '..evveeDDDeDDvD....',
      '.edDee...oe..oDe...',
      '.eeee....eo....eo..',
      '.doeo...ee.........',
      'oo.eo...o..........',
      '...o...............',
    ],
    [
      '......oo.D..e.e....',
      '......nnD....DDo...',
      '.......nDonoDoD.o..',
      '........nndonoDdo..',
      '.........ednDDDe...',
      '..........bvvbe....',
      '..........oDBbBo...',
      '..........evvvdD...',
      '.....oooeddvLBD....',
      '...ebLBLBBdbvcd....',
      '..evBbBBbbvdbve....',
      '..ovbbbbbbBbdD.....',
      '..ovbddvdDbbve.....',
      '..DvdeoDDDedbe.....',
      '.eDeeo...eeoeDD....',
      'ed..e...ee....eD...',
      'e...e..e........o..',
      '...oo.o............',
      '...................',
    ],
    [
      '.........o..o.o....',
      '......DDDD..eeDo...',
      '......Dae.D..eD....',
      '.......eaodonoDeo..',
      '........eaadDend...',
      '..........bDndo....',
      '..........evbnvo...',
      '...........DbBBD...',
      '..........evbdo....',
      '....eddoeddvLAD....',
      '..odLBBLBBdbvcd....',
      '..evbbbBbbbdvve....',
      '..ovbvbbvbBdve.....',
      '..evbDDdddbvDo.....',
      '.oDeeeooeevd.......',
      '.oD..eo...DD.......',
      'ooe.oe..oeoD.......',
      '........o..DD......',
      '............eo.....',
    ],
    [
      '.........o..o.o....',
      '......DDDD..eeDo...',
      '......Dae.D..eD....',
      '.......eaodonoDeo..',
      '........eaadDend...',
      '.........odDndo....',
      '..........evbnvo...',
      '...........DbBBe...',
      '..........evbdo....',
      '....oDooeddvLAD....',
      '...DLLBLBBdbvcd....',
      '..evBbBBbBndbbe....',
      '..ovbdbbbbbDdD.....',
      '...DbdvvDvbDDe.....',
      '..eddeeDevdeo......',
      '..Dooeo..Deee......',
      '..D...e..Dee.......',
      '.oo...oe.Do........',
      '........oe.........',
    ]
  ];

  // ---------------------------------------------------------------- wolf
  // The wolf den's pack: a low-slung side-view predator, amber-eyed, in the
  // same 3-frame stand/run set the deer and rabbit use (left = flipH).
  const WOPAL = {
    '.': null,
    'o': '#262b38', // outline
    'y': '#6f778c', // coat mid
    'Y': '#8f97ac', // coat light (lit from above)
    'd': '#4d5468', // coat shade (flank)
    'c': '#dfe4ef', // pale throat / belly / muzzle
    'e': '#f2b03c', // eye
    'n': '#171a22', // nose
  };
  const wolfBody = [
    '...........o.o..',
    '..........oYoYo.',
    '.o........oYYYo.',
    'oYo....ooooYYYYo',
    'oYYo..oYYYYYYYeo',
    '.oYYooYYYYYYYccn',
    '..oYYdddddYYcco.',
    '...oddddddddco..',
    '...oddddddddco..',
    '...ocddcccddco..',
  ];
  const wolfStand = wolfBody.concat([
    '...oyo...oyyo...',
    '...oyo...oyyo...',
    '...ooo...ooo....',
  ]);
  const wolfRunA = wolfBody.concat([
    '..oyo....oyyo...',
    '.oyo......oyyo..',
    '.ooo......ooo...',
  ]);
  const wolfRunB = wolfBody.concat([
    '....oyo.oyyo....',
    '....oyo..oyyo...',
    '....ooo..ooo....',
  ]);

  // Birds: the rookery's flock. Tiny, so a perched frame plus two wing frames
  // is the whole set; the game draws them above the ground on their own alt.
  const BIPAL = {
    '.': null,
    'o': '#232734', // outline
    'y': '#4d5566', // feather mid
    'Y': '#77809a', // feather light
    'c': '#cfd6e4', // pale breast
    'n': '#e0a63c', // beak
  };
  const birdPerch = [
    '..oo.....',
    '.oYYo....',
    'oyYYyon..',
    'oyyyyco..',
    '.oyyco...',
    '..o.o....',
  ];
  const birdFlyA = [
    'oo.....oo',
    '.oy...yo.',
    '.oyYYYyon',
    '..oyccyo.',
    '...ooo...',
  ];
  const birdFlyB = [
    '.........',
    '..oo.oo..',
    '.oyYYYyon',
    'oyyyccyo.',
    '.oo...oo.',
  ];

  const rabbitSet = bakeClips({ idle: rabbitIdle, hop: rabbitHop, rise: rabbitRise }, RBPAL);
  const deerSet = bakeClips({ idle: deerIdle, graze: deerGraze, run: deerRun }, DEPAL);
  const wolfSet = bakeClips({ idle: [wolfStand], run: [wolfRunA, wolfRunB] }, WOPAL);
  const birdSet = bakeClips({ idle: [birdPerch], fly: [birdFlyA, birdFlyB] }, BIPAL);

  Object.assign(SPRITES, {
    rabbit: { right: rabbitSet, left: mapClips(rabbitSet, flipH) },
    wolf: { right: wolfSet, left: mapClips(wolfSet, flipH) },
    bird: { right: birdSet, left: mapClips(birdSet, flipH) },
    deer: { right: deerSet, left: mapClips(deerSet, flipH) },
    imp: [bake(imp1, IPAL), bake(imp2, IPAL)],
  });

  // ---------------------------------------------------------------- the camps' wolves
  // PLACEHOLDER LOOKS, derived from the wolf rather than drawn: the buff
  // camp's ALPHA is the same grids washed toward silver, the epic camp's
  // DIRE WOLF is them washed toward a dark red and doubled to 32x26 with
  // nearest-neighbour, so it reads as twice the animal at any zoom. Each
  // wants its own grid one day (the concept-art skill); until then
  // drawAnimal (draw-world.js) treats them as a wolf with a bigger frame.
  const W = window.SPRITES.wolf;
  const alphaSkin = (s) => wash(s, '#dfe6f4', 0.45);
  const direSkin = (s) => double(wash(s, '#5a1e2c', 0.5));
  window.SPRITES.alpha = { right: mapClips(W.right, alphaSkin), left: mapClips(W.left, alphaSkin) };
  window.SPRITES.dire = { right: mapClips(W.right, direSkin), left: mapClips(W.left, direSkin) };
})();
