'use strict';
// The ground's furniture: the pine and its 24 wind frames (and the one atlas
// every pine on screen draws from), stumps, rocks, ore, the mine, the berry
// bush's four states, the camps' dead snags and the wolf den.
(() => {
  const { bake, flipH } = SPR;

  // ---------------------------------------------------------------- trees
  const TPAL = {
    '.': null,
    'o': '#22383a', // outline
    'g': '#2f5c4b', // pine dark
    'G': '#3f7a5c', // pine mid
    'L': '#549468', // pine light
    'w': '#eef4fb', // snow
    'W': '#ffffff', // snow bright
    's': '#c9dcee', // snow shade
    'u': '#6f4d38', // trunk
    'U': '#4a3324', // trunk dark
    'c': '#d9ad72', // stump cut face
    'C': '#b9884f', // stump ring
    'v': '#503626', // bark dark
  };

  // The living pine: one tree in 24 bend frames, 27x37 on its own palette
  // (TPAL above still dresses the stump it leaves). Wider and taller than the
  // 16x24 pine it replaced, so it draws at (px - 5, py - 21) - base on the
  // tile's bottom edge, canopy overhanging the tile above. Which frame a tree
  // wears is not its own business: treeFrame() in js/draw-world.js reads it off
  // the wind wave crossing the field, so the forest rustles as one.
  const TSPAL = {
    '.': null,
    'o': '#040205', // outline
    'k': '#052122', // deepest shade under a bough
    'd': '#0e3c36', // pine darkest
    'g': '#184b3e', // pine dark
    'h': '#265c47', // pine mid-dark
    'G': '#2e6c44', // pine mid
    'L': '#3a7c4d', // pine light
    'l': '#67a584', // needle highlight
    'm': '#76a9ab', // frosted needle
    's': '#b4dfe6', // snow shade
    'S': '#c7f4e8', // snow mid
    'w': '#d8f8f6', // snow
    'U': '#462422', // trunk dark
    'u': '#6f4a2d', // trunk
  };
  // 24 bend frames of one snowy pine, 27x37 - and every one of them is the
  // SAME tree. They used to be sixteen crops of sixteen variant trees, which
  // meant a swaying pine morphed its own branches from frame to frame and a
  // gust could not push a stand of them anywhere together; these are
  // docs/media/new_media/001.png leaning by different amounts, so a front
  // crossing the treeline lays every tree inside it over the same way.
  // The array is a LADDER, not a cycle: index 0 is the tree thrown fully
  // left, 23 fully right, 11 and 12 are it standing straight up. That is what
  // lets treeFrame() (js/draw-world.js) map the wind's SIGNED sway onto an
  // index directly - a frame here is a lean, not a phase.
  // The lean is a tip-loaded cantilever rounded per row: a row h of the way
  // up from the base moves 2.6 * (3h^2 - h^3) / 2 px, which is zero slope
  // where the trunk meets the snow, all of the curve in the crown, and 6px of
  // travel at the tip from one end of the ladder to the other. Rows round at
  // different heights, so 21 of the 24 frames are distinct pixels.
  const treeSway = [
    [ //  0  tip left  3px
      '..........o................',
      '..........owo..............',
      '..........owo..............',
      '.........oswso.............',
      '.........owwwo.............',
      '........oswwwso............',
      '........owwwwwo............',
      '.......owwwwswwo...........',
      '......oswgswswsso..........',
      '.......okgssggso...........',
      '......ohhggggGggo..........',
      '......owGGGGdGGGGho........',
      '.....owwwGwGGGwwGsso.......',
      '.....ookhwGGGsGwwkko.......',
      '......ohdwdGwskGwho........',
      '......oGdkgGwkdkkLo........',
      '.....owSghwGdgGGGGwo.......',
      '....owwGGwwdgGGGGSwwo......',
      '...owwGwGGGGGggwGGLwwo.....',
      '..oGLLdhwGGdGGwwGGwGGwo....',
      '...ooogwwGwLGGGwwGdsko.....',
      '....odwwhdwwwskGwsddo......',
      '...ogddwdhdGwskddssdGo.....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ //  1  tip left  2px
      '...........o...............',
      '..........owo..............',
      '..........owo..............',
      '.........oswso.............',
      '.........owwwo.............',
      '........oswwwso............',
      '........owwwwwo............',
      '.......owwwwswwo...........',
      '......oswgswswsso..........',
      '.......okgssggso...........',
      '.......ohhggggGggo.........',
      '......owGGGGdGGGGho........',
      '.....owwwGwGGGwwGsso.......',
      '.....ookhwGGGsGwwkko.......',
      '......ohdwdGwskGwho........',
      '......oGdkgGwkdkkLo........',
      '.....owSghwGdgGGGGwo.......',
      '....owwGGwwdgGGGGSwwo......',
      '...owwGwGGGGGggwGGLwwo.....',
      '..oGLLdhwGGdGGwwGGwGGwo....',
      '...ooogwwGwLGGGwwGdsko.....',
      '....odwwhdwwwskGwsddo......',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ //  2  tip left  2px
      '...........o...............',
      '..........owo..............',
      '..........owo..............',
      '.........oswso.............',
      '.........owwwo.............',
      '........oswwwso............',
      '........owwwwwo............',
      '.......owwwwswwo...........',
      '.......oswgswswsso.........',
      '........okgssggso..........',
      '.......ohhggggGggo.........',
      '......owGGGGdGGGGho........',
      '.....owwwGwGGGwwGsso.......',
      '.....ookhwGGGsGwwkko.......',
      '......ohdwdGwskGwho........',
      '......oGdkgGwkdkkLo........',
      '.....owSghwGdgGGGGwo.......',
      '....owwGGwwdgGGGGSwwo......',
      '...owwGwGGGGGggwGGLwwo.....',
      '..oGLLdhwGGdGGwwGGwGGwo....',
      '...ooogwwGwLGGGwwGdsko.....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ //  3  tip left  2px
      '...........o...............',
      '..........owo..............',
      '..........owo..............',
      '.........oswso.............',
      '.........owwwo.............',
      '........oswwwso............',
      '.........owwwwwo...........',
      '........owwwwswwo..........',
      '.......oswgswswsso.........',
      '........okgssggso..........',
      '.......ohhggggGggo.........',
      '......owGGGGdGGGGho........',
      '.....owwwGwGGGwwGsso.......',
      '.....ookhwGGGsGwwkko.......',
      '......ohdwdGwskGwho........',
      '......oGdkgGwkdkkLo........',
      '.....owSghwGdgGGGGwo.......',
      '....owwGGwwdgGGGGSwwo......',
      '...owwGwGGGGGggwGGLwwo.....',
      '..oGLLdhwGGdGGwwGGwGGwo....',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ //  4  tip left  2px
      '...........o...............',
      '..........owo..............',
      '..........owo..............',
      '..........oswso............',
      '..........owwwo............',
      '.........oswwwso...........',
      '.........owwwwwo...........',
      '........owwwwswwo..........',
      '.......oswgswswsso.........',
      '........okgssggso..........',
      '.......ohhggggGggo.........',
      '......owGGGGdGGGGho........',
      '.....owwwGwGGGwwGsso.......',
      '.....ookhwGGGsGwwkko.......',
      '......ohdwdGwskGwho........',
      '......oGdkgGwkdkkLo........',
      '.....owSghwGdgGGGGwo.......',
      '....owwGGwwdgGGGGSwwo......',
      '...owwGwGGGGGggwGGLwwo.....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ //  5  tip left  1px
      '............o..............',
      '...........owo.............',
      '...........owo.............',
      '..........oswso............',
      '..........owwwo............',
      '.........oswwwso...........',
      '.........owwwwwo...........',
      '........owwwwswwo..........',
      '.......oswgswswsso.........',
      '........okgssggso..........',
      '.......ohhggggGggo.........',
      '......owGGGGdGGGGho........',
      '.....owwwGwGGGwwGsso.......',
      '.....ookhwGGGsGwwkko.......',
      '......ohdwdGwskGwho........',
      '......oGdkgGwkdkkLo........',
      '.....owSghwGdgGGGGwo.......',
      '....owwGGwwdgGGGGSwwo......',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ //  6  tip left  1px
      '............o..............',
      '...........owo.............',
      '...........owo.............',
      '..........oswso............',
      '..........owwwo............',
      '.........oswwwso...........',
      '.........owwwwwo...........',
      '........owwwwswwo..........',
      '.......oswgswswsso.........',
      '........okgssggso..........',
      '.......ohhggggGggo.........',
      '......owGGGGdGGGGho........',
      '.....owwwGwGGGwwGsso.......',
      '.....ookhwGGGsGwwkko.......',
      '......ohdwdGwskGwho........',
      '......oGdkgGwkdkkLo........',
      '......owSghwGdgGGGGwo......',
      '.....owwGGwwdgGGGGSwwo.....',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ //  7  tip left  1px
      '............o..............',
      '...........owo.............',
      '...........owo.............',
      '..........oswso............',
      '..........owwwo............',
      '.........oswwwso...........',
      '.........owwwwwo...........',
      '........owwwwswwo..........',
      '.......oswgswswsso.........',
      '........okgssggso..........',
      '.......ohhggggGggo.........',
      '......owGGGGdGGGGho........',
      '.....owwwGwGGGwwGsso.......',
      '......ookhwGGGsGwwkko......',
      '.......ohdwdGwskGwho.......',
      '.......oGdkgGwkdkkLo.......',
      '......owSghwGdgGGGGwo......',
      '.....owwGGwwdgGGGGSwwo.....',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ //  8  tip left  1px
      '............o..............',
      '...........owo.............',
      '...........owo.............',
      '..........oswso............',
      '..........owwwo............',
      '.........oswwwso...........',
      '.........owwwwwo...........',
      '........owwwwswwo..........',
      '.......oswgswswsso.........',
      '........okgssggso..........',
      '........ohhggggGggo........',
      '.......owGGGGdGGGGho.......',
      '......owwwGwGGGwwGsso......',
      '......ookhwGGGsGwwkko......',
      '.......ohdwdGwskGwho.......',
      '.......oGdkgGwkdkkLo.......',
      '......owSghwGdgGGGGwo......',
      '.....owwGGwwdgGGGGSwwo.....',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ //  9  tip left  1px
      '............o..............',
      '...........owo.............',
      '...........owo.............',
      '...........oswso...........',
      '...........owwwo...........',
      '..........oswwwso..........',
      '..........owwwwwo..........',
      '.........owwwwswwo.........',
      '........oswgswswsso........',
      '.........okgssggso.........',
      '........ohhggggGggo........',
      '.......owGGGGdGGGGho.......',
      '......owwwGwGGGwwGsso......',
      '......ookhwGGGsGwwkko......',
      '.......ohdwdGwskGwho.......',
      '.......oGdkgGwkdkkLo.......',
      '......owSghwGdgGGGGwo......',
      '.....owwGGwwdgGGGGSwwo.....',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 10  tip upright
      '.............o.............',
      '............owo............',
      '............owo............',
      '...........oswso...........',
      '...........owwwo...........',
      '..........oswwwso..........',
      '..........owwwwwo..........',
      '.........owwwwswwo.........',
      '........oswgswswsso........',
      '.........okgssggso.........',
      '........ohhggggGggo........',
      '.......owGGGGdGGGGho.......',
      '......owwwGwGGGwwGsso......',
      '......ookhwGGGsGwwkko......',
      '.......ohdwdGwskGwho.......',
      '.......oGdkgGwkdkkLo.......',
      '......owSghwGdgGGGGwo......',
      '.....owwGGwwdgGGGGSwwo.....',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 11  tip upright
      '.............o.............',
      '............owo............',
      '............owo............',
      '...........oswso...........',
      '...........owwwo...........',
      '..........oswwwso..........',
      '..........owwwwwo..........',
      '.........owwwwswwo.........',
      '........oswgswswsso........',
      '.........okgssggso.........',
      '........ohhggggGggo........',
      '.......owGGGGdGGGGho.......',
      '......owwwGwGGGwwGsso......',
      '......ookhwGGGsGwwkko......',
      '.......ohdwdGwskGwho.......',
      '.......oGdkgGwkdkkLo.......',
      '......owSghwGdgGGGGwo......',
      '.....owwGGwwdgGGGGSwwo.....',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 12  tip upright
      '.............o.............',
      '............owo............',
      '............owo............',
      '...........oswso...........',
      '...........owwwo...........',
      '..........oswwwso..........',
      '..........owwwwwo..........',
      '.........owwwwswwo.........',
      '........oswgswswsso........',
      '.........okgssggso.........',
      '........ohhggggGggo........',
      '.......owGGGGdGGGGho.......',
      '......owwwGwGGGwwGsso......',
      '......ookhwGGGsGwwkko......',
      '.......ohdwdGwskGwho.......',
      '.......oGdkgGwkdkkLo.......',
      '......owSghwGdgGGGGwo......',
      '.....owwGGwwdgGGGGSwwo.....',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 13  tip upright
      '.............o.............',
      '............owo............',
      '............owo............',
      '...........oswso...........',
      '...........owwwo...........',
      '..........oswwwso..........',
      '..........owwwwwo..........',
      '.........owwwwswwo.........',
      '........oswgswswsso........',
      '.........okgssggso.........',
      '........ohhggggGggo........',
      '.......owGGGGdGGGGho.......',
      '......owwwGwGGGwwGsso......',
      '......ookhwGGGsGwwkko......',
      '.......ohdwdGwskGwho.......',
      '.......oGdkgGwkdkkLo.......',
      '......owSghwGdgGGGGwo......',
      '.....owwGGwwdgGGGGSwwo.....',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 14  tip right 1px
      '..............o............',
      '.............owo...........',
      '.............owo...........',
      '...........oswso...........',
      '...........owwwo...........',
      '..........oswwwso..........',
      '..........owwwwwo..........',
      '.........owwwwswwo.........',
      '........oswgswswsso........',
      '.........okgssggso.........',
      '........ohhggggGggo........',
      '.......owGGGGdGGGGho.......',
      '......owwwGwGGGwwGsso......',
      '......ookhwGGGsGwwkko......',
      '.......ohdwdGwskGwho.......',
      '.......oGdkgGwkdkkLo.......',
      '......owSghwGdgGGGGwo......',
      '.....owwGGwwdgGGGGSwwo.....',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 15  tip right 1px
      '..............o............',
      '.............owo...........',
      '.............owo...........',
      '............oswso..........',
      '............owwwo..........',
      '...........oswwwso.........',
      '...........owwwwwo.........',
      '..........owwwwswwo........',
      '.........oswgswswsso.......',
      '..........okgssggso........',
      '........ohhggggGggo........',
      '.......owGGGGdGGGGho.......',
      '......owwwGwGGGwwGsso......',
      '......ookhwGGGsGwwkko......',
      '.......ohdwdGwskGwho.......',
      '.......oGdkgGwkdkkLo.......',
      '......owSghwGdgGGGGwo......',
      '.....owwGGwwdgGGGGSwwo.....',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 16  tip right 1px
      '..............o............',
      '.............owo...........',
      '.............owo...........',
      '............oswso..........',
      '............owwwo..........',
      '...........oswwwso.........',
      '...........owwwwwo.........',
      '..........owwwwswwo........',
      '.........oswgswswsso.......',
      '..........okgssggso........',
      '.........ohhggggGggo.......',
      '........owGGGGdGGGGho......',
      '.......owwwGwGGGwwGsso.....',
      '......ookhwGGGsGwwkko......',
      '.......ohdwdGwskGwho.......',
      '.......oGdkgGwkdkkLo.......',
      '......owSghwGdgGGGGwo......',
      '.....owwGGwwdgGGGGSwwo.....',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 17  tip right 1px
      '..............o............',
      '.............owo...........',
      '.............owo...........',
      '............oswso..........',
      '............owwwo..........',
      '...........oswwwso.........',
      '...........owwwwwo.........',
      '..........owwwwswwo........',
      '.........oswgswswsso.......',
      '..........okgssggso........',
      '.........ohhggggGggo.......',
      '........owGGGGdGGGGho......',
      '.......owwwGwGGGwwGsso.....',
      '.......ookhwGGGsGwwkko.....',
      '........ohdwdGwskGwho......',
      '........oGdkgGwkdkkLo......',
      '......owSghwGdgGGGGwo......',
      '.....owwGGwwdgGGGGSwwo.....',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 18  tip right 1px
      '..............o............',
      '.............owo...........',
      '.............owo...........',
      '............oswso..........',
      '............owwwo..........',
      '...........oswwwso.........',
      '...........owwwwwo.........',
      '..........owwwwswwo........',
      '.........oswgswswsso.......',
      '..........okgssggso........',
      '.........ohhggggGggo.......',
      '........owGGGGdGGGGho......',
      '.......owwwGwGGGwwGsso.....',
      '.......ookhwGGGsGwwkko.....',
      '........ohdwdGwskGwho......',
      '........oGdkgGwkdkkLo......',
      '.......owSghwGdgGGGGwo.....',
      '......owwGGwwdgGGGGSwwo....',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 19  tip right 2px
      '...............o...........',
      '..............owo..........',
      '..............owo..........',
      '............oswso..........',
      '............owwwo..........',
      '...........oswwwso.........',
      '...........owwwwwo.........',
      '..........owwwwswwo........',
      '.........oswgswswsso.......',
      '..........okgssggso........',
      '.........ohhggggGggo.......',
      '........owGGGGdGGGGho......',
      '.......owwwGwGGGwwGsso.....',
      '.......ookhwGGGsGwwkko.....',
      '........ohdwdGwskGwho......',
      '........oGdkgGwkdkkLo......',
      '.......owSghwGdgGGGGwo.....',
      '......owwGGwwdgGGGGSwwo....',
      '.....owwGwGGGGGggwGGLwwo...',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 20  tip right 2px
      '...............o...........',
      '..............owo..........',
      '..............owo..........',
      '.............oswso.........',
      '.............owwwo.........',
      '............oswwwso........',
      '...........owwwwwo.........',
      '..........owwwwswwo........',
      '.........oswgswswsso.......',
      '..........okgssggso........',
      '.........ohhggggGggo.......',
      '........owGGGGdGGGGho......',
      '.......owwwGwGGGwwGsso.....',
      '.......ookhwGGGsGwwkko.....',
      '........ohdwdGwskGwho......',
      '........oGdkgGwkdkkLo......',
      '.......owSghwGdgGGGGwo.....',
      '......owwGGwwdgGGGGSwwo....',
      '.....owwGwGGGGGggwGGLwwo...',
      '....oGLLdhwGGdGGwwGGwGGwo..',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 21  tip right 2px
      '...............o...........',
      '..............owo..........',
      '..............owo..........',
      '.............oswso.........',
      '.............owwwo.........',
      '............oswwwso........',
      '............owwwwwo........',
      '...........owwwwswwo.......',
      '.........oswgswswsso.......',
      '..........okgssggso........',
      '.........ohhggggGggo.......',
      '........owGGGGdGGGGho......',
      '.......owwwGwGGGwwGsso.....',
      '.......ookhwGGGsGwwkko.....',
      '........ohdwdGwskGwho......',
      '........oGdkgGwkdkkLo......',
      '.......owSghwGdgGGGGwo.....',
      '......owwGGwwdgGGGGSwwo....',
      '.....owwGwGGGGGggwGGLwwo...',
      '....oGLLdhwGGdGGwwGGwGGwo..',
      '.....ooogwwGwLGGGwwGdsko...',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 22  tip right 2px
      '...............o...........',
      '..............owo..........',
      '..............owo..........',
      '.............oswso.........',
      '.............owwwo.........',
      '............oswwwso........',
      '............owwwwwo........',
      '...........owwwwswwo.......',
      '..........oswgswswsso......',
      '...........okgssggso.......',
      '.........ohhggggGggo.......',
      '........owGGGGdGGGGho......',
      '.......owwwGwGGGwwGsso.....',
      '.......ookhwGGGsGwwkko.....',
      '........ohdwdGwskGwho......',
      '........oGdkgGwkdkkLo......',
      '.......owSghwGdgGGGGwo.....',
      '......owwGGwwdgGGGGSwwo....',
      '.....owwGwGGGGGggwGGLwwo...',
      '....oGLLdhwGGdGGwwGGwGGwo..',
      '.....ooogwwGwLGGGwwGdsko...',
      '......odwwhdwwwskGwsddo....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 23  tip right 3px
      '................o..........',
      '..............owo..........',
      '..............owo..........',
      '.............oswso.........',
      '.............owwwo.........',
      '............oswwwso........',
      '............owwwwwo........',
      '...........owwwwswwo.......',
      '..........oswgswswsso......',
      '...........okgssggso.......',
      '..........ohhggggGggo......',
      '........owGGGGdGGGGho......',
      '.......owwwGwGGGwwGsso.....',
      '.......ookhwGGGsGwwkko.....',
      '........ohdwdGwskGwho......',
      '........oGdkgGwkdkkLo......',
      '.......owSghwGdgGGGGwo.....',
      '......owwGGwwdgGGGGSwwo....',
      '.....owwGwGGGGGggwGGLwwo...',
      '....oGLLdhwGGdGGwwGGwGGwo..',
      '.....ooogwwGwLGGGwwGdsko...',
      '......odwwhdwwwskGwsddo....',
      '.....ogddwdhdGwskddssdGo...',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
  ];

  const stump = [
    '.....oooooo.....',
    '....occcccco....',
    '....ocCCCCco....',
    '....occCCcco....',
    '....ovuuuuvo....',
    '....ovuUUuvo....',
    '.....osssso.....',
    '................',
  ];

  // ---------------------------------------------------------------- rocks
  const RPAL = {
    '.': null,
    'o': '#3a3f52', // outline
    'y': '#8b93a8', // rock mid
    'Y': '#a8b0c4', // rock light
    'v': '#666d84', // rock dark
    'w': '#eef4fb',
    'W': '#ffffff',
    's': '#c9dcee',
  };

  const rock1 = [
    '................',
    '.....owwWo......',
    '....owwwwso.....',
    '...oYwwYyyo.....',
    '..oYYyyyyyvo....',
    '..oYyyyyvvvo....',
    '..oyyyvyvvvo....',
    '...ovvvvvvo.....',
    '....ssssss......',
  ];

  const rock2 = [
    '................',
    '......oWwo......',
    '....owwwwwso....',
    '...oYwwwYyyo....',
    '..oYYwYyyyyvo...',
    '..oYYyyyyvvvo...',
    '..oYyyyvyvvvo...',
    '..oyyvvvvvvvo...',
    '...ovvvvvvvo....',
    '....sssssss.....',
  ];

  // ---------------------------------------------------------------- gold ore
  const GOPAL = {
    '.': null,
    'o': '#3a3f52',
    'y': '#8b93a8',
    'Y': '#a8b0c4',
    'v': '#666d84',
    'w': '#eef4fb',
    'W': '#ffffff',
    's': '#c9dcee',
    'n': '#d8a850', // gold
    'N': '#f2cc6a', // gold bright
  };
  const goldOre = [
    '................',
    '......oWwo......',
    '....owwwwwso....',
    '...oYwwnNYyo....',
    '..oYYwYyNnyvo...',
    '..oYYnNyyvnvo...',
    '..oYynvyNyvvo...',
    '..oyyvnNvyvvo...',
    '...ovvvnvvvo....',
    '....sssssss.....',
  ];

  // ---------------------------------------------------------------- gold mine (32x32, occupies 2x2 tiles)
  const MIPAL = {
    '.': null,
    'o': '#2c2c3c', // outline
    'y': '#8b93a8', // rock mid
    'Y': '#a8b0c4', // rock light
    'v': '#666d84', // rock dark
    'V': '#4e5266', // rock deep
    'k': '#0c0f1e', // shaft black
    'K': '#1d2438', // shaft edge
    'u': '#8a6142', // timber
    'U': '#a3794f', // timber light
    'n': '#d8a850', // gold vein
    'N': '#f2cc6a', // gold bright
    'w': '#eef4fb', // snow
    'W': '#ffffff',
    's': '#c9dcee', // snow shade
  };
  const mine = [
    '..............WWw...............',
    '............owwwwwo.............',
    '...........owwwwwwyo............',
    '..........oYwwwwYyyvo...........',
    '.........oYYwwwYYyyyvo..........',
    '........oYYYwwYYyyyyvvo.........',
    '.......oYYYYYYYyyyyvvvvo........',
    '......oYYYYnYYyyyyyvvvvvo.......',
    '.....oYYYYNnYyyyyyyvvvvvvo......',
    '....oYYYYYnYyyyyyyyyvvvvVVo.....',
    '...oYYYwwYYyyyyNnyyyvvvVVVVo....',
    '..oYYYwwwYyyyyyNyyyyvvvvVVVVo...',
    '..oYYYYYyyyyyyyyyyyyvvvvVVVVo...',
    '.oYYYYYyyyoKKKKKKKKovyvvVVVVVo..',
    '.oYYYnNyyoKkkkkkkkkKovvvVVVVVo..',
    '.oYYYYnyyoUuuuuuuuuUovvVVVVVVo..',
    '.oYYYyyyyoUukkkkkkuUovvvVVVVVo..',
    'oYYYyyyyyoUukkkkkkuUoyvvVVVVVVo.',
    'oYYyyyyyyoUukkkkkkuUovvvVVVVVVo.',
    'oYyyyNnyyoUukkkkkkuUovvVvVVVVVo.',
    'oYyyyynyyoUukkkkkkuUovvvVVVVVVo.',
    'oYyyyyyyyoUukkkkkkuUovvVVVVVVVo.',
    'oyyyyyyyyoUukkkkkkuUonvVVVVVVVo.',
    'oyyyynyyyoUukkkkkkuUoNnVVVVVVVo.',
    'oyyyyyyyyoUukkkkkkuUovvVVVVVVVo.',
    'oyyyyyyyyoUukkkkkkuUovvVVVVVVVo.',
    '.oyyyyyyyoUukkkkkkuUovvVVVVVVo..',
    '.oyyyyyyyoUukkkkkkuUovvVVVVVo...',
    '..ooyyyyyoUukkkkkkuUovvVVVoo....',
    '....ooooooooskkkksoooooooo......',
    '.....ssssssssssssssssssss.......',
    '................................',
  ];

  // ---------------------------------------------------------------- bush
  const BPAL = {
    '.': null,
    'o': '#22383a',
    'g': '#3a6b52',
    'G': '#4c8560',
    'r': '#d6454f', // berry
    'R': '#f2707a', // berry shine
    'w': '#eef4fb',
    's': '#c9dcee',
    'b': '#b9d9a4', // bud: pale, unripe
    'd': '#7b2c3a', // berry coming in: dull, no shine yet
  };

  const bush = [
    '................',
    '....owwwso......',
    '...ogwGgGgo.....',
    '..ogGrGGgrGo....',
    '..oGgRGgGgGgo...',
    '..ogGgGrGRgGo...',
    '...ogGgGgGgo....',
    '....ssssss......',
  ];
  const bushEmpty = [
    '................',
    '....owwwso......',
    '...ogwGgGgo.....',
    '..ogGgGGggGo....',
    '..oGgGGgGgGgo...',
    '..ogGgGgGGgGo...',
    '...ogGgGgGgo....',
    '....ssssss......',
  ];
  // the regrow clock, read off the plant (BUSH_BUD_T / BUSH_RIPEN_T,
  // js/world.js): pale buds where the berries will be, then the berries
  // back but dull, then `bush` again. Same silhouette, only the four berry
  // pixels change, so the stage reads without the bush seeming to move.
  const bushBud = [
    '................',
    '....owwwso......',
    '...ogwGgGgo.....',
    '..ogGbGGgbGo....',
    '..oGgGGgGgGgo...',
    '..ogGgGbGbgGo...',
    '...ogGgGgGgo....',
    '....ssssss......',
  ];
  const bushRipen = [
    '................',
    '....owwwso......',
    '...ogwGgGgo.....',
    '..ogGdGGgdGo....',
    '..oGgdGgGgGgo...',
    '..ogGgGdGdgGo...',
    '...ogGgGgGgo....',
    '....ssssss......',
  ];

  // Dead trees: the rookery's bare snags. Same 16x24 footprint as a pine so
  // they draw at py-8 in the same band, but stripped to grey wood and snow.
  const DTPAL = {
    '.': null,
    'o': '#2a2018', // outline
    'u': '#6b5a48', // dead wood
    'U': '#4b3d30', // dead wood dark
    'v': '#8a7761', // lit bark
    'w': '#eef4fb', // snow
    's': '#c9dcee', // snow shade
  };
  const deadTree1 = [
    '................',
    '.......ow.......',
    '..w....ou.......',
    '.ouo...ov...w...',
    '..ovo..ov..ouo..',
    '...ovo.ov.ovo...',
    '....ovoovoovo...',
    '.....ovuvuvo....',
    '..w...ouvuo.....',
    '.ouo..ouvuo.ww..',
    '..ovo.ouvuo.ou..',
    '...ovooUvUoovo..',
    '....ovuUvUuvo...',
    '......ouvUo.....',
    '......ouvUo.....',
    '......ouUUo.....',
    '.....oouUUoo....',
    '.....ovuUUvo....',
    '.....ovuUUvo....',
    '.....ouUUUuo....',
    '....oouUUUuoo...',
    '....owwUUUwwo...',
    '....osswwwsso...',
    '.....ssssss.....',
  ];
  const deadTree2 = [
    '................',
    '...........w....',
    '....w.....ou....',
    '...ouo....ov....',
    '....ovo..ovo....',
    '.....ovooovo....',
    '..w...ovuvo.....',
    '.ouo..ouvuo.....',
    '..ovo.ouvuo.w...',
    '...ovooUvUoouo..',
    '....ovuUvUuovo..',
    '......ouvUuvo...',
    '......ouvUo.....',
    '......ouUUo.....',
    '......ouUUo.....',
    '.....oouUUo.....',
    '.....ovuUUoo....',
    '.....ovuUUvo....',
    '.....ouUUUvo....',
    '.....ouUUUuo....',
    '....oouUUUuoo...',
    '....owwUUUwwo...',
    '....osswwwsso...',
    '.....ssssss.....',
  ];

  // The wolf den's mouth: a snow-capped rock mound with a black throat and a
  // picked-over bone at the lip. 16x12, drawn at py+4 like a rock.
  const DNPAL = {
    '.': null,
    'o': '#2b3040', // outline
    'y': '#7b8398', // rock mid
    'Y': '#99a1b6', // rock light
    'v': '#5a6176', // rock dark
    'k': '#12151f', // the dark inside
    'b': '#e6e2d4', // bone
    'w': '#eef4fb', // snow
    's': '#c9dcee', // snow shade
  };
  const den = [
    '................',
    '.....owwwwo.....',
    '...oowwwwwwoo...',
    '..owwwwwwwwwwo..',
    '.oswwwwwwwwwwso.',
    'oYsswyyyyywsssYo',
    'oYyyyokkkoyyyyYo',
    'oYyyokkkkkoyyyYo',
    'ovyyokkkkkoyyyvo',
    'ovvyokkkkkoyyvvo',
    '.ovvokkkkkovvvo.',
    '..ooobkkkboooo..',
  ];
  // baked once, up here, because both the array and the atlas below need it
  const treeSpr = treeSway.map((f) => bake(f, TSPAL));

  Object.assign(SPRITES, {
    // 24 bend frames, not 2 variants: treeFrame() picks one off the wind wave.
    // They are drawn through `treeAtlas` below, never from this array - it is
    // kept because the atlas is built out of it and a single frame is handy.
    tree: treeSpr,
    // ONE texture for every pine on screen. A wide-open view holds a thousand
    // trees, and a drawImage whose source canvas differs from the last one
    // cannot be batched: on a GTX 1060 the sixteen separate canvases cost 97
    // fps against 199 for the same sprites drawn from a single source. So the
    // frames are laid out side by side and render() blits sub-rects of this.
    // FORTY-EIGHT of them: the second run of 24 is the first run mirrored, and
    // treeFrame() sends half the forest into it off the tile's hash. Now that
    // every frame is one tree rather than sixteen variants, that mirror is the
    // only thing left keeping a stand from reading as one stamp repeated - and
    // it is free, because a wider atlas is still a single texture. A mirrored
    // tree leans the other way, so the ladder runs backwards over there and
    // treeFrame() reverses the index when it crosses.
    // `fw`/`fh` ride on the canvas so the caller needs no second constant.
    treeAtlas: (() => {
      const fr = treeSpr.concat(treeSpr.map(flipH));
      const fw = fr[0].width, fh = fr[0].height;
      const c = document.createElement('canvas');
      c.width = fw * fr.length; c.height = fh;
      const g = c.getContext('2d');
      g.imageSmoothingEnabled = false;
      fr.forEach((f, i) => g.drawImage(f, i * fw, 0));
      c.fw = fw; c.fh = fh;
      return c;
    })(),
    stump: bake(stump, TPAL),
    rock: [bake(rock1, RPAL), bake(rock2, RPAL)],
    goldOre: bake(goldOre, GOPAL),
    mine: bake(mine, MIPAL),
    bush: bake(bush, BPAL),
    bushEmpty: bake(bushEmpty, BPAL),
    bushBud: bake(bushBud, BPAL),
    bushRipen: bake(bushRipen, BPAL),
    deadTree: [bake(deadTree1, DTPAL), bake(deadTree2, DTPAL)],
    den: bake(den, DNPAL),
  });
})();
