'use strict';
// The ground's furniture: the pine and its 24 wind frames (and the one atlas
// every pine on screen draws from), stumps, the dead gold ore and mine, the berry
// bush's four states, the camps' dead snags, the wolf den and the hog hut.
(() => {
  const { bake, flipH } = SPR;

  // ---------------------------------------------------------------- trees
  const TPAL = {
    '.': null,
    'o': '#22383a', // outline
    'g': '#2f5c4b', // pine dark
    'G': '#3f7a5c', // pine mid
    'L': '#549468', // pine light
    'w': '#eef4fb', // snow
    'W': '#ffffff', // snow bright
    's': '#c9dcee', // snow shade
    'u': '#6f4d38', // trunk
    'U': '#4a3324', // trunk dark
    'c': '#d9ad72', // stump cut face
    'C': '#b9884f', // stump ring
    'v': '#503626', // bark dark
  };

  // The living pine: one tree in 24 bend frames, 27x37 on its own palette
  // (TPAL above still dresses the stump it leaves). TSPAL is the SOURCE the
  // forest's palettes are filtered from (treePals, below the frames) - no
  // pine draws in it as is. Wider and taller than the
  // 16x24 pine it replaced, so it draws at (px - 5, py - 21) - base on the
  // tile's bottom edge, canopy overhanging the tile above. Which frame a tree
  // wears is not its own business: treeFrame() in js/draw-world.js reads it off
  // the wind wave crossing the field, so the forest rustles as one.
  const TSPAL = {
    '.': null,
    'o': '#040205', // outline
    'k': '#052122', // deepest shade under a bough
    'd': '#0e3c36', // pine darkest
    'g': '#184b3e', // pine dark
    'h': '#265c47', // pine mid-dark
    'G': '#2e6c44', // pine mid
    'L': '#3a7c4d', // pine light
    'l': '#67a584', // needle highlight
    'm': '#76a9ab', // frosted needle
    's': '#b4dfe6', // snow shade
    'S': '#c7f4e8', // snow mid
    'w': '#d8f8f6', // snow
    'U': '#462422', // trunk dark
    'u': '#6f4a2d', // trunk
  };
  // 24 bend frames of one snowy pine, 27x37 - and every one of them is the
  // SAME tree. They used to be sixteen crops of sixteen variant trees, which
  // meant a swaying pine morphed its own branches from frame to frame and a
  // gust could not push a stand of them anywhere together; these are
  // docs/media/new_media/001.png leaning by different amounts, so a front
  // crossing the treeline lays every tree inside it over the same way.
  // The array is a LADDER, not a cycle: index 0 is the tree thrown fully
  // left, 23 fully right, 11 and 12 are it standing straight up. That is what
  // lets treeFrame() (js/draw-world.js) map the wind's SIGNED sway onto an
  // index directly - a frame here is a lean, not a phase.
  // The lean is a tip-loaded cantilever rounded per row: a row h of the way
  // up from the base moves 2.6 * (3h^2 - h^3) / 2 px, which is zero slope
  // where the trunk meets the snow, all of the curve in the crown, and 6px of
  // travel at the tip from one end of the ladder to the other. Rows round at
  // different heights, so 21 of the 24 frames are distinct pixels.
  const treeSway = [
    [ //  0  tip left  3px
      '..........o................',
      '..........owo..............',
      '..........owo..............',
      '.........oswso.............',
      '.........owwwo.............',
      '........oswwwso............',
      '........owwwwwo............',
      '.......owwwwswwo...........',
      '......oswgswswsso..........',
      '.......okgssggso...........',
      '......ohhggggGggo..........',
      '......owGGGGdGGGGho........',
      '.....owwwGwGGGwwGsso.......',
      '.....ookhwGGGsGwwkko.......',
      '......ohdwdGwskGwho........',
      '......oGdkgGwkdkkLo........',
      '.....owSghwGdgGGGGwo.......',
      '....owwGGwwdgGGGGSwwo......',
      '...owwGwGGGGGggwGGLwwo.....',
      '..oGLLdhwGGdGGwwGGwGGwo....',
      '...ooogwwGwLGGGwwGdsko.....',
      '....odwwhdwwwskGwsddo......',
      '...ogddwdhdGwskddssdGo.....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ //  1  tip left  2px
      '...........o...............',
      '..........owo..............',
      '..........owo..............',
      '.........oswso.............',
      '.........owwwo.............',
      '........oswwwso............',
      '........owwwwwo............',
      '.......owwwwswwo...........',
      '......oswgswswsso..........',
      '.......okgssggso...........',
      '.......ohhggggGggo.........',
      '......owGGGGdGGGGho........',
      '.....owwwGwGGGwwGsso.......',
      '.....ookhwGGGsGwwkko.......',
      '......ohdwdGwskGwho........',
      '......oGdkgGwkdkkLo........',
      '.....owSghwGdgGGGGwo.......',
      '....owwGGwwdgGGGGSwwo......',
      '...owwGwGGGGGggwGGLwwo.....',
      '..oGLLdhwGGdGGwwGGwGGwo....',
      '...ooogwwGwLGGGwwGdsko.....',
      '....odwwhdwwwskGwsddo......',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ //  2  tip left  2px
      '...........o...............',
      '..........owo..............',
      '..........owo..............',
      '.........oswso.............',
      '.........owwwo.............',
      '........oswwwso............',
      '........owwwwwo............',
      '.......owwwwswwo...........',
      '.......oswgswswsso.........',
      '........okgssggso..........',
      '.......ohhggggGggo.........',
      '......owGGGGdGGGGho........',
      '.....owwwGwGGGwwGsso.......',
      '.....ookhwGGGsGwwkko.......',
      '......ohdwdGwskGwho........',
      '......oGdkgGwkdkkLo........',
      '.....owSghwGdgGGGGwo.......',
      '....owwGGwwdgGGGGSwwo......',
      '...owwGwGGGGGggwGGLwwo.....',
      '..oGLLdhwGGdGGwwGGwGGwo....',
      '...ooogwwGwLGGGwwGdsko.....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ //  3  tip left  2px
      '...........o...............',
      '..........owo..............',
      '..........owo..............',
      '.........oswso.............',
      '.........owwwo.............',
      '........oswwwso............',
      '.........owwwwwo...........',
      '........owwwwswwo..........',
      '.......oswgswswsso.........',
      '........okgssggso..........',
      '.......ohhggggGggo.........',
      '......owGGGGdGGGGho........',
      '.....owwwGwGGGwwGsso.......',
      '.....ookhwGGGsGwwkko.......',
      '......ohdwdGwskGwho........',
      '......oGdkgGwkdkkLo........',
      '.....owSghwGdgGGGGwo.......',
      '....owwGGwwdgGGGGSwwo......',
      '...owwGwGGGGGggwGGLwwo.....',
      '..oGLLdhwGGdGGwwGGwGGwo....',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ //  4  tip left  2px
      '...........o...............',
      '..........owo..............',
      '..........owo..............',
      '..........oswso............',
      '..........owwwo............',
      '.........oswwwso...........',
      '.........owwwwwo...........',
      '........owwwwswwo..........',
      '.......oswgswswsso.........',
      '........okgssggso..........',
      '.......ohhggggGggo.........',
      '......owGGGGdGGGGho........',
      '.....owwwGwGGGwwGsso.......',
      '.....ookhwGGGsGwwkko.......',
      '......ohdwdGwskGwho........',
      '......oGdkgGwkdkkLo........',
      '.....owSghwGdgGGGGwo.......',
      '....owwGGwwdgGGGGSwwo......',
      '...owwGwGGGGGggwGGLwwo.....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ //  5  tip left  1px
      '............o..............',
      '...........owo.............',
      '...........owo.............',
      '..........oswso............',
      '..........owwwo............',
      '.........oswwwso...........',
      '.........owwwwwo...........',
      '........owwwwswwo..........',
      '.......oswgswswsso.........',
      '........okgssggso..........',
      '.......ohhggggGggo.........',
      '......owGGGGdGGGGho........',
      '.....owwwGwGGGwwGsso.......',
      '.....ookhwGGGsGwwkko.......',
      '......ohdwdGwskGwho........',
      '......oGdkgGwkdkkLo........',
      '.....owSghwGdgGGGGwo.......',
      '....owwGGwwdgGGGGSwwo......',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ //  6  tip left  1px
      '............o..............',
      '...........owo.............',
      '...........owo.............',
      '..........oswso............',
      '..........owwwo............',
      '.........oswwwso...........',
      '.........owwwwwo...........',
      '........owwwwswwo..........',
      '.......oswgswswsso.........',
      '........okgssggso..........',
      '.......ohhggggGggo.........',
      '......owGGGGdGGGGho........',
      '.....owwwGwGGGwwGsso.......',
      '.....ookhwGGGsGwwkko.......',
      '......ohdwdGwskGwho........',
      '......oGdkgGwkdkkLo........',
      '......owSghwGdgGGGGwo......',
      '.....owwGGwwdgGGGGSwwo.....',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ //  7  tip left  1px
      '............o..............',
      '...........owo.............',
      '...........owo.............',
      '..........oswso............',
      '..........owwwo............',
      '.........oswwwso...........',
      '.........owwwwwo...........',
      '........owwwwswwo..........',
      '.......oswgswswsso.........',
      '........okgssggso..........',
      '.......ohhggggGggo.........',
      '......owGGGGdGGGGho........',
      '.....owwwGwGGGwwGsso.......',
      '......ookhwGGGsGwwkko......',
      '.......ohdwdGwskGwho.......',
      '.......oGdkgGwkdkkLo.......',
      '......owSghwGdgGGGGwo......',
      '.....owwGGwwdgGGGGSwwo.....',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ //  8  tip left  1px
      '............o..............',
      '...........owo.............',
      '...........owo.............',
      '..........oswso............',
      '..........owwwo............',
      '.........oswwwso...........',
      '.........owwwwwo...........',
      '........owwwwswwo..........',
      '.......oswgswswsso.........',
      '........okgssggso..........',
      '........ohhggggGggo........',
      '.......owGGGGdGGGGho.......',
      '......owwwGwGGGwwGsso......',
      '......ookhwGGGsGwwkko......',
      '.......ohdwdGwskGwho.......',
      '.......oGdkgGwkdkkLo.......',
      '......owSghwGdgGGGGwo......',
      '.....owwGGwwdgGGGGSwwo.....',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ //  9  tip left  1px
      '............o..............',
      '...........owo.............',
      '...........owo.............',
      '...........oswso...........',
      '...........owwwo...........',
      '..........oswwwso..........',
      '..........owwwwwo..........',
      '.........owwwwswwo.........',
      '........oswgswswsso........',
      '.........okgssggso.........',
      '........ohhggggGggo........',
      '.......owGGGGdGGGGho.......',
      '......owwwGwGGGwwGsso......',
      '......ookhwGGGsGwwkko......',
      '.......ohdwdGwskGwho.......',
      '.......oGdkgGwkdkkLo.......',
      '......owSghwGdgGGGGwo......',
      '.....owwGGwwdgGGGGSwwo.....',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 10  tip upright
      '.............o.............',
      '............owo............',
      '............owo............',
      '...........oswso...........',
      '...........owwwo...........',
      '..........oswwwso..........',
      '..........owwwwwo..........',
      '.........owwwwswwo.........',
      '........oswgswswsso........',
      '.........okgssggso.........',
      '........ohhggggGggo........',
      '.......owGGGGdGGGGho.......',
      '......owwwGwGGGwwGsso......',
      '......ookhwGGGsGwwkko......',
      '.......ohdwdGwskGwho.......',
      '.......oGdkgGwkdkkLo.......',
      '......owSghwGdgGGGGwo......',
      '.....owwGGwwdgGGGGSwwo.....',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 11  tip upright
      '.............o.............',
      '............owo............',
      '............owo............',
      '...........oswso...........',
      '...........owwwo...........',
      '..........oswwwso..........',
      '..........owwwwwo..........',
      '.........owwwwswwo.........',
      '........oswgswswsso........',
      '.........okgssggso.........',
      '........ohhggggGggo........',
      '.......owGGGGdGGGGho.......',
      '......owwwGwGGGwwGsso......',
      '......ookhwGGGsGwwkko......',
      '.......ohdwdGwskGwho.......',
      '.......oGdkgGwkdkkLo.......',
      '......owSghwGdgGGGGwo......',
      '.....owwGGwwdgGGGGSwwo.....',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 12  tip upright
      '.............o.............',
      '............owo............',
      '............owo............',
      '...........oswso...........',
      '...........owwwo...........',
      '..........oswwwso..........',
      '..........owwwwwo..........',
      '.........owwwwswwo.........',
      '........oswgswswsso........',
      '.........okgssggso.........',
      '........ohhggggGggo........',
      '.......owGGGGdGGGGho.......',
      '......owwwGwGGGwwGsso......',
      '......ookhwGGGsGwwkko......',
      '.......ohdwdGwskGwho.......',
      '.......oGdkgGwkdkkLo.......',
      '......owSghwGdgGGGGwo......',
      '.....owwGGwwdgGGGGSwwo.....',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 13  tip upright
      '.............o.............',
      '............owo............',
      '............owo............',
      '...........oswso...........',
      '...........owwwo...........',
      '..........oswwwso..........',
      '..........owwwwwo..........',
      '.........owwwwswwo.........',
      '........oswgswswsso........',
      '.........okgssggso.........',
      '........ohhggggGggo........',
      '.......owGGGGdGGGGho.......',
      '......owwwGwGGGwwGsso......',
      '......ookhwGGGsGwwkko......',
      '.......ohdwdGwskGwho.......',
      '.......oGdkgGwkdkkLo.......',
      '......owSghwGdgGGGGwo......',
      '.....owwGGwwdgGGGGSwwo.....',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 14  tip right 1px
      '..............o............',
      '.............owo...........',
      '.............owo...........',
      '...........oswso...........',
      '...........owwwo...........',
      '..........oswwwso..........',
      '..........owwwwwo..........',
      '.........owwwwswwo.........',
      '........oswgswswsso........',
      '.........okgssggso.........',
      '........ohhggggGggo........',
      '.......owGGGGdGGGGho.......',
      '......owwwGwGGGwwGsso......',
      '......ookhwGGGsGwwkko......',
      '.......ohdwdGwskGwho.......',
      '.......oGdkgGwkdkkLo.......',
      '......owSghwGdgGGGGwo......',
      '.....owwGGwwdgGGGGSwwo.....',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 15  tip right 1px
      '..............o............',
      '.............owo...........',
      '.............owo...........',
      '............oswso..........',
      '............owwwo..........',
      '...........oswwwso.........',
      '...........owwwwwo.........',
      '..........owwwwswwo........',
      '.........oswgswswsso.......',
      '..........okgssggso........',
      '........ohhggggGggo........',
      '.......owGGGGdGGGGho.......',
      '......owwwGwGGGwwGsso......',
      '......ookhwGGGsGwwkko......',
      '.......ohdwdGwskGwho.......',
      '.......oGdkgGwkdkkLo.......',
      '......owSghwGdgGGGGwo......',
      '.....owwGGwwdgGGGGSwwo.....',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 16  tip right 1px
      '..............o............',
      '.............owo...........',
      '.............owo...........',
      '............oswso..........',
      '............owwwo..........',
      '...........oswwwso.........',
      '...........owwwwwo.........',
      '..........owwwwswwo........',
      '.........oswgswswsso.......',
      '..........okgssggso........',
      '.........ohhggggGggo.......',
      '........owGGGGdGGGGho......',
      '.......owwwGwGGGwwGsso.....',
      '......ookhwGGGsGwwkko......',
      '.......ohdwdGwskGwho.......',
      '.......oGdkgGwkdkkLo.......',
      '......owSghwGdgGGGGwo......',
      '.....owwGGwwdgGGGGSwwo.....',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 17  tip right 1px
      '..............o............',
      '.............owo...........',
      '.............owo...........',
      '............oswso..........',
      '............owwwo..........',
      '...........oswwwso.........',
      '...........owwwwwo.........',
      '..........owwwwswwo........',
      '.........oswgswswsso.......',
      '..........okgssggso........',
      '.........ohhggggGggo.......',
      '........owGGGGdGGGGho......',
      '.......owwwGwGGGwwGsso.....',
      '.......ookhwGGGsGwwkko.....',
      '........ohdwdGwskGwho......',
      '........oGdkgGwkdkkLo......',
      '......owSghwGdgGGGGwo......',
      '.....owwGGwwdgGGGGSwwo.....',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 18  tip right 1px
      '..............o............',
      '.............owo...........',
      '.............owo...........',
      '............oswso..........',
      '............owwwo..........',
      '...........oswwwso.........',
      '...........owwwwwo.........',
      '..........owwwwswwo........',
      '.........oswgswswsso.......',
      '..........okgssggso........',
      '.........ohhggggGggo.......',
      '........owGGGGdGGGGho......',
      '.......owwwGwGGGwwGsso.....',
      '.......ookhwGGGsGwwkko.....',
      '........ohdwdGwskGwho......',
      '........oGdkgGwkdkkLo......',
      '.......owSghwGdgGGGGwo.....',
      '......owwGGwwdgGGGGSwwo....',
      '....owwGwGGGGGggwGGLwwo....',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 19  tip right 2px
      '...............o...........',
      '..............owo..........',
      '..............owo..........',
      '............oswso..........',
      '............owwwo..........',
      '...........oswwwso.........',
      '...........owwwwwo.........',
      '..........owwwwswwo........',
      '.........oswgswswsso.......',
      '..........okgssggso........',
      '.........ohhggggGggo.......',
      '........owGGGGdGGGGho......',
      '.......owwwGwGGGwwGsso.....',
      '.......ookhwGGGsGwwkko.....',
      '........ohdwdGwskGwho......',
      '........oGdkgGwkdkkLo......',
      '.......owSghwGdgGGGGwo.....',
      '......owwGGwwdgGGGGSwwo....',
      '.....owwGwGGGGGggwGGLwwo...',
      '...oGLLdhwGGdGGwwGGwGGwo...',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 20  tip right 2px
      '...............o...........',
      '..............owo..........',
      '..............owo..........',
      '.............oswso.........',
      '.............owwwo.........',
      '............oswwwso........',
      '...........owwwwwo.........',
      '..........owwwwswwo........',
      '.........oswgswswsso.......',
      '..........okgssggso........',
      '.........ohhggggGggo.......',
      '........owGGGGdGGGGho......',
      '.......owwwGwGGGwwGsso.....',
      '.......ookhwGGGsGwwkko.....',
      '........ohdwdGwskGwho......',
      '........oGdkgGwkdkkLo......',
      '.......owSghwGdgGGGGwo.....',
      '......owwGGwwdgGGGGSwwo....',
      '.....owwGwGGGGGggwGGLwwo...',
      '....oGLLdhwGGdGGwwGGwGGwo..',
      '....ooogwwGwLGGGwwGdsko....',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 21  tip right 2px
      '...............o...........',
      '..............owo..........',
      '..............owo..........',
      '.............oswso.........',
      '.............owwwo.........',
      '............oswwwso........',
      '............owwwwwo........',
      '...........owwwwswwo.......',
      '.........oswgswswsso.......',
      '..........okgssggso........',
      '.........ohhggggGggo.......',
      '........owGGGGdGGGGho......',
      '.......owwwGwGGGwwGsso.....',
      '.......ookhwGGGsGwwkko.....',
      '........ohdwdGwskGwho......',
      '........oGdkgGwkdkkLo......',
      '.......owSghwGdgGGGGwo.....',
      '......owwGGwwdgGGGGSwwo....',
      '.....owwGwGGGGGggwGGLwwo...',
      '....oGLLdhwGGdGGwwGGwGGwo..',
      '.....ooogwwGwLGGGwwGdsko...',
      '.....odwwhdwwwskGwsddo.....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 22  tip right 2px
      '...............o...........',
      '..............owo..........',
      '..............owo..........',
      '.............oswso.........',
      '.............owwwo.........',
      '............oswwwso........',
      '............owwwwwo........',
      '...........owwwwswwo.......',
      '..........oswgswswsso......',
      '...........okgssggso.......',
      '.........ohhggggGggo.......',
      '........owGGGGdGGGGho......',
      '.......owwwGwGGGwwGsso.....',
      '.......ookhwGGGsGwwkko.....',
      '........ohdwdGwskGwho......',
      '........oGdkgGwkdkkLo......',
      '.......owSghwGdgGGGGwo.....',
      '......owwGGwwdgGGGGSwwo....',
      '.....owwGwGGGGGggwGGLwwo...',
      '....oGLLdhwGGdGGwwGGwGGwo..',
      '.....ooogwwGwLGGGwwGdsko...',
      '......odwwhdwwwskGwsddo....',
      '....ogddwdhdGwskddssdGo....',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
    [ // 23  tip right 3px
      '................o..........',
      '..............owo..........',
      '..............owo..........',
      '.............oswso.........',
      '.............owwwo.........',
      '............oswwwso........',
      '............owwwwwo........',
      '...........owwwwswwo.......',
      '..........oswgswswsso......',
      '...........okgssggso.......',
      '..........ohhggggGggo......',
      '........owGGGGdGGGGho......',
      '.......owwwGwGGGwwGsso.....',
      '.......ookhwGGGsGwwkko.....',
      '........ohdwdGwskGwho......',
      '........oGdkgGwkdkkLo......',
      '.......owSghwGdgGGGGwo.....',
      '......owwGGwwdgGGGGSwwo....',
      '.....owwGwGGGGGggwGGLwwo...',
      '....oGLLdhwGGdGGwwGGwGGwo..',
      '.....ooogwwGwLGGGwwGdsko...',
      '......odwwhdwwwskGwsddo....',
      '.....ogddwdhdGwskddssdGo...',
      '....ogddkdGddwLdddkdgdo....',
      '...owGGGdLwGdkkgGdGGGGwo...',
      '..owwwwGGGGGhdgdGGGGGwwoo..',
      '..owwsGGwwGGwGgGGwGdGGswo..',
      '.owLGGhwwwwwwlGwwwGdGwGLwo.',
      'oGLgkGwshwsswwGGGssdwGkLLwo',
      '.oooGwlgdwsGssgGGGsdGSkoooo',
      '...oGGGokGGdGsoddLLodLwo...',
      '...oooo.oLLoGoUooGo.oooo...',
      '.........ooUoUUUoo.........',
      '..........oUUuuUo..........',
      '..........oUuuuUo..........',
      '..........oUuuuUo..........',
      '...........ooooo...........',
    ],
  ];

  const stump = [
    '.....oooooo.....',
    '....occcccco....',
    '....ocCCCCco....',
    '....occCCcco....',
    '....ovuuuuvo....',
    '....ovuUUuvo....',
    '.....osssso.....',
    '................',
  ];

  // ---------------------------------------------------------------- gold ore
  const GOPAL = {
    '.': null,
    'o': '#3a3f52',
    'y': '#8b93a8',
    'Y': '#a8b0c4',
    'v': '#666d84',
    'w': '#eef4fb',
    'W': '#ffffff',
    's': '#c9dcee',
    'n': '#d8a850', // gold
    'N': '#f2cc6a', // gold bright
  };
  const goldOre = [
    '................',
    '......oWwo......',
    '....owwwwwso....',
    '...oYwwnNYyo....',
    '..oYYwYyNnyvo...',
    '..oYYnNyyvnvo...',
    '..oYynvyNyvvo...',
    '..oyyvnNvyvvo...',
    '...ovvvnvvvo....',
    '....sssssss.....',
  ];

  // ---------------------------------------------------------------- gold mine (32x32, occupies 2x2 tiles)
  const MIPAL = {
    '.': null,
    'o': '#2c2c3c', // outline
    'y': '#8b93a8', // rock mid
    'Y': '#a8b0c4', // rock light
    'v': '#666d84', // rock dark
    'V': '#4e5266', // rock deep
    'k': '#0c0f1e', // shaft black
    'K': '#1d2438', // shaft edge
    'u': '#8a6142', // timber
    'U': '#a3794f', // timber light
    'n': '#d8a850', // gold vein
    'N': '#f2cc6a', // gold bright
    'w': '#eef4fb', // snow
    'W': '#ffffff',
    's': '#c9dcee', // snow shade
  };
  const mine = [
    '..............WWw...............',
    '............owwwwwo.............',
    '...........owwwwwwyo............',
    '..........oYwwwwYyyvo...........',
    '.........oYYwwwYYyyyvo..........',
    '........oYYYwwYYyyyyvvo.........',
    '.......oYYYYYYYyyyyvvvvo........',
    '......oYYYYnYYyyyyyvvvvvo.......',
    '.....oYYYYNnYyyyyyyvvvvvvo......',
    '....oYYYYYnYyyyyyyyyvvvvVVo.....',
    '...oYYYwwYYyyyyNnyyyvvvVVVVo....',
    '..oYYYwwwYyyyyyNyyyyvvvvVVVVo...',
    '..oYYYYYyyyyyyyyyyyyvvvvVVVVo...',
    '.oYYYYYyyyoKKKKKKKKovyvvVVVVVo..',
    '.oYYYnNyyoKkkkkkkkkKovvvVVVVVo..',
    '.oYYYYnyyoUuuuuuuuuUovvVVVVVVo..',
    '.oYYYyyyyoUukkkkkkuUovvvVVVVVo..',
    'oYYYyyyyyoUukkkkkkuUoyvvVVVVVVo.',
    'oYYyyyyyyoUukkkkkkuUovvvVVVVVVo.',
    'oYyyyNnyyoUukkkkkkuUovvVvVVVVVo.',
    'oYyyyynyyoUukkkkkkuUovvvVVVVVVo.',
    'oYyyyyyyyoUukkkkkkuUovvVVVVVVVo.',
    'oyyyyyyyyoUukkkkkkuUonvVVVVVVVo.',
    'oyyyynyyyoUukkkkkkuUoNnVVVVVVVo.',
    'oyyyyyyyyoUukkkkkkuUovvVVVVVVVo.',
    'oyyyyyyyyoUukkkkkkuUovvVVVVVVVo.',
    '.oyyyyyyyoUukkkkkkuUovvVVVVVVo..',
    '.oyyyyyyyoUukkkkkkuUovvVVVVVo...',
    '..ooyyyyyoUukkkkkkuUovvVVVoo....',
    '....ooooooooskkkksoooooooo......',
    '.....ssssssssssssssssssss.......',
    '................................',
  ];

  // ---------------------------------------------------------------- bush
  const BPAL = {
    '.': null,
    'o': '#22383a',
    'g': '#3a6b52',
    'G': '#4c8560',
    'r': '#d6454f', // berry
    'R': '#f2707a', // berry shine
    'w': '#eef4fb',
    's': '#c9dcee',
    'b': '#b9d9a4', // bud: pale, unripe
    'd': '#7b2c3a', // berry coming in: dull, no shine yet
  };

  const bush = [
    '................',
    '....owwwso......',
    '...ogwGgGgo.....',
    '..ogGrGGgrGo....',
    '..oGgRGgGgGgo...',
    '..ogGgGrGRgGo...',
    '...ogGgGgGgo....',
    '....ssssss......',
  ];
  const bushEmpty = [
    '................',
    '....owwwso......',
    '...ogwGgGgo.....',
    '..ogGgGGggGo....',
    '..oGgGGgGgGgo...',
    '..ogGgGgGGgGo...',
    '...ogGgGgGgo....',
    '....ssssss......',
  ];
  // the regrow clock, read off the plant (BUSH_BUD_T / BUSH_RIPEN_T,
  // js/world.js): pale buds where the berries will be, then the berries
  // back but dull, then `bush` again. Same silhouette, only the four berry
  // pixels change, so the stage reads without the bush seeming to move.
  const bushBud = [
    '................',
    '....owwwso......',
    '...ogwGgGgo.....',
    '..ogGbGGgbGo....',
    '..oGgGGgGgGgo...',
    '..ogGgGbGbgGo...',
    '...ogGgGgGgo....',
    '....ssssss......',
  ];
  const bushRipen = [
    '................',
    '....owwwso......',
    '...ogwGgGgo.....',
    '..ogGdGGgdGo....',
    '..oGgdGgGgGgo...',
    '..ogGgGdGdgGo...',
    '...ogGgGgGgo....',
    '....ssssss......',
  ];

  // Dead trees: the rookery's bare snags. Same 16x24 footprint as a pine so
  // they draw at py-8 in the same band, but stripped to grey wood and snow.
  const DTPAL = {
    '.': null,
    'o': '#2a2018', // outline
    'u': '#6b5a48', // dead wood
    'U': '#4b3d30', // dead wood dark
    'v': '#8a7761', // lit bark
    'w': '#eef4fb', // snow
    's': '#c9dcee', // snow shade
  };
  const deadTree1 = [
    '................',
    '.......ow.......',
    '..w....ou.......',
    '.ouo...ov...w...',
    '..ovo..ov..ouo..',
    '...ovo.ov.ovo...',
    '....ovoovoovo...',
    '.....ovuvuvo....',
    '..w...ouvuo.....',
    '.ouo..ouvuo.ww..',
    '..ovo.ouvuo.ou..',
    '...ovooUvUoovo..',
    '....ovuUvUuvo...',
    '......ouvUo.....',
    '......ouvUo.....',
    '......ouUUo.....',
    '.....oouUUoo....',
    '.....ovuUUvo....',
    '.....ovuUUvo....',
    '.....ouUUUuo....',
    '....oouUUUuoo...',
    '....owwUUUwwo...',
    '....osswwwsso...',
    '.....ssssss.....',
  ];
  const deadTree2 = [
    '................',
    '...........w....',
    '....w.....ou....',
    '...ouo....ov....',
    '....ovo..ovo....',
    '.....ovooovo....',
    '..w...ovuvo.....',
    '.ouo..ouvuo.....',
    '..ovo.ouvuo.w...',
    '...ovooUvUoouo..',
    '....ovuUvUuovo..',
    '......ouvUuvo...',
    '......ouvUo.....',
    '......ouUUo.....',
    '......ouUUo.....',
    '.....oouUUo.....',
    '.....ovuUUoo....',
    '.....ovuUUvo....',
    '.....ouUUUvo....',
    '.....ouUUUuo....',
    '....oouUUUuoo...',
    '....owwUUUwwo...',
    '....osswwwsso...',
    '.....ssssss.....',
  ];

  // The wolf den: A ROCK MAW of docs/media/concepts/den-concepts-1.png - a
  // snow-capped boulder hill grown into a cave, icicle fangs over a wide black
  // mouth, bones at the lip. 32x21 over its two tiles (OBJECTS.den's w: the
  // anchor and a part to its right), the lip row on the tiles' foot, so it is
  // drawn at py - 4. The WOLF DEN and the DIRE HOLLOW both stand one.
  const DNPAL = {
    '.': null,
    'o': '#2b3040', // outline
    'y': '#7b8398', // rock mid
    'Y': '#99a1b6', // rock light
    'v': '#5a6176', // rock dark
    'k': '#12151f', // the dark inside
    'K': '#232838', // ...and its rim
    'i': '#dcecff', // icicle fangs
    'b': '#e6e2d4', // bone
    'B': '#b9b2a0', // bone shade
    'w': '#eef4fb', // snow
    's': '#c9dcee', // snow shade
  };
  const den = [
    '............oooooo..............',
    '..........oowwwwwwoo.ooo........',
    '......oowwwwwwwwwwwwowwwoo......',
    '.....owwwwwwwwwwwwwwwwwwwwo.....',
    '....owwwwwwwwwwwwwwwwwwwwwwo....',
    '...ossswwwwwwwwwwwwwwwwwwssso...',
    '..oYysssswwwwwsssswwwwssssyYYo..',
    '..oYyyyyssssssoooossssssyyyyYo..',
    '.oYyyyyyyyyooKKKKKKooyyyyyyyyYo.',
    '.oYyyyyyyyoiKiKkkKiKioyyyyyyyYo.',
    '.oyyyyyyyoKikiKkkKikiKoyyyyyyyo.',
    'oYyyyyyyoKkkkikkkkikkkKoyyyyyyYo',
    'oYyyyyyoKkkkkkkkkkkkkkkKoyyyyyvo',
    'ovyyyyyokkkkkkkkkkkkkkkkoyyyyvvo',
    'ovyyYyyokkkkkkkkkkkkkkkkoyyyvvvo',
    'ovvyyyyokkkkkkkkkkkkkkkkoyYyvvvo',
    'ovvvyyyokkkkkkkkkkkkkkkkoyyvvvvo',
    '.ovvvyyokkkkkkkkkkkkkkkkoyvvvvo.',
    '.ovvvvvokkkkkkkkkkkkkkkkovvvvvo.',
    '..ooovvoKkkkkkkkkkkkkkkKovvooo..',
    '.....ooobBKkkkkkkkkkKBbooo......',
  ];
  // The forest's palettes: TSPAL run through colour filters in OKLCH, never
  // redrawn (docs/media/concepts/tree-filters-2.png picked B, C and D). The
  // drawn pine's contrast ran from a near-black outline to near-white snow,
  // which made it read as a foreground object; each variant lowers that
  // contrast first and keeps the colour (a grey pine turns to mud under the
  // night grade). B: a dark muted green outline, the needle darks lifted, the
  // snow a soft blue-grey. C: B with the needles' hue shifted by value -
  // shadows toward teal, lights toward yellow-green. D: C at 80% colour with
  // a muted trunk. Each of the three comes in three TONES for how deep in the
  // forest a tree stands (treeTone, js/draw/ground.js): the deep as filtered,
  // the ring inside the edge lighter, the edge lighter again. Nine pines in
  // ten stand deep, so the deep tone IS the picked look and the edge is what
  // moves - darkening the deep instead would darken the whole forest.
  const TREE_ROLE = { o: 'outline', k: 'needle', d: 'needle', g: 'needle', h: 'needle', G: 'needle', L: 'needle', l: 'needle', m: 'needle', s: 'snow', S: 'snow', w: 'snow', U: 'trunk', u: 'trunk' };
  const TREE_TONES = [0.07, 0.035, 0]; // needle L shift: edge, inner ring, deep
  const treePals = (() => {
    const lin = (c) => (c <= 0.04045 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4));
    const gam = (c) => (c <= 0.0031308 ? 12.92 * c : 1.055 * Math.pow(c, 1 / 2.4) - 0.055);
    const toLch = (hex) => {
      const [r, g, b] = [1, 3, 5].map((i) => lin(parseInt(hex.slice(i, i + 2), 16) / 255));
      const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
      const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
      const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);
      const A = 1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s;
      const B = 0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s;
      return { L: 0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s, C: Math.hypot(A, B), h: (Math.atan2(B, A) * 180 / Math.PI + 360) % 360 };
    };
    const toHex = ({ L, C, h }) => {
      const A = C * Math.cos(h * Math.PI / 180), B = C * Math.sin(h * Math.PI / 180);
      const l = (L + 0.3963377774 * A + 0.2158037573 * B) ** 3;
      const m = (L - 0.1055613458 * A - 0.0638541728 * B) ** 3;
      const s = (L - 0.0894841775 * A - 1.291485548 * B) ** 3;
      return '#' + [4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
        -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
        -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s]
        .map((c) => Math.round(Math.max(0, Math.min(1, gam(c))) * 255).toString(16).padStart(2, '0')).join('');
    };
    const lerp = (a, b, t) => a + (b - a) * t;
    const lerpH = (a, b, t) => (a + (((b - a + 540) % 360) - 180) * t + 360) % 360;
    // each filter maps (role, lch, the role's L range before it ran) to lch
    const outline = (r, c) => r !== 'outline' ? c : { L: 0.37, C: 0.045, h: 168 };
    const liftDarks = (r, c, st) => r !== 'needle' ? c : { ...c, L: 0.40 + (c.L - st.needle.min) * (st.needle.max - 0.40) / (st.needle.max - st.needle.min) };
    const softSnow = (r, c, st) => r !== 'snow' ? c : { L: 0.80 + (c.L - st.snow.min) * 0.10 / (st.snow.max - st.snow.min), C: 0.028, h: 235 };
    const hueShift = (r, c, st) => { if (r !== 'needle') return c; const t = (c.L - st.needle.min) / (st.needle.max - st.needle.min); return { ...c, h: lerpH(c.h, lerpH(195, 128, t), 0.6) }; };
    const colour = (k) => (r, c) => r !== 'needle' ? c : { ...c, C: c.C * k };
    const trunk = (r, c) => r !== 'trunk' ? c : { L: lerp(c.L, 0.50, 0.4), C: c.C * 0.65, h: c.h };
    const tone = (d) => (r, c) => r !== 'needle' ? c : { ...c, L: c.L + d };
    const run = (filters) => {
      const lch = {};
      for (const k in TREE_ROLE) lch[k] = toLch(TSPAL[k]);
      for (const f of filters) {
        const st = {};
        for (const role of ['needle', 'snow']) {
          const Ls = Object.keys(lch).filter((k) => TREE_ROLE[k] === role).map((k) => lch[k].L);
          st[role] = { min: Math.min(...Ls), max: Math.max(...Ls) };
        }
        for (const k in lch) lch[k] = f(TREE_ROLE[k], lch[k], st);
      }
      const pal = { '.': null };
      for (const k in lch) pal[k] = toHex(lch[k]);
      return pal;
    };
    const B = [outline, liftDarks, softSnow], C = B.concat([hueShift]), D = C.concat([colour(0.8), trunk]);
    const out = [];
    for (const v of [B, C, D]) for (const t of TREE_TONES) out.push(run(v.concat([tone(t)])));
    return out; // row = variant * 3 + tone
  })();
  // baked once, up here, because both the array and the atlas below need it:
  // one run of 24 frames per palette row
  const treeRows = treePals.map((pal) => treeSway.map((f) => bake(f, pal)));
  const treeSpr = treeRows[2]; // variant B, deep tone (the filtered look itself) - the pine a single frame stands for
  // ---------------------------------------------------------------- the hog hut
  // The HOG HUT camp's anchor (CAMPS.hut, js/world.js): a snow-roofed log
  // hut with a smoking chimney, 35x35 on a 2x2 footprint, drawn centred over
  // the anchor tile and the one to its right. Eight frames of the chimney's smoke, straight off
  // docs/media/new_media5/hog-hut-chimney-moving.png at 1:1 - the source
  // is already game-scale pixel art with hard alpha, so nothing is resampled.
  const HHPAL = {
    '.': null,
    'a': '#020102',
    'b': '#1b0318',
    'c': '#352a32',
    'd': '#4c3738',
    'e': '#573636',
    'f': '#463f36',
    'g': '#444230',
    'h': '#4d403e',
    'i': '#654234',
    'j': '#61574c',
    'k': '#6b6557',
    'l': '#866145',
    'm': '#61727c',
    'n': '#837250',
    'o': '#848075',
    'p': '#899ba6',
    'q': '#98aeb4',
    'r': '#a3badd',
    's': '#a6cbe2',
    't': '#d4f3f8',
  };
  const hogHut = [
    [
      '.........................a.........',
      '........................ata........',
      '.......................atsta.......',
      '.......................asmsa.......',
      '........................aaa........',
      '........................apa........',
      '........................apa........',
      '.............aaaaaa....aqma........',
      '......aaaaaarttttttaa.aqma.........',
      '.aaaaastttttttttttttttama..........',
      '.akkkkotkkqttttttttttaqmaaa........',
      '..aahhkktokksjohhttttamcsttaa......',
      '..ahaajjkkhhdkkttttttsaasttttaa....',
      '..akahaachotkkkhhttttttttttttttaa..',
      '..akajhhaakckkkkkkkkotttsssssjffa..',
      '..akaajjhhaahhhtttttokjkjppaaaaa...',
      '..akhtaajjhhaadqsssjjjaaaaaacaca...',
      '..aklntjaaakjdaakkaaaaccahhahaha...',
      '..akalkqpanaajhaaaaccafcahhahaha...',
      '..akaaajjoanjakahaaddafcahhahkaa...',
      '..akaliaajanjncakdaddafcakhjhkaa...',
      '..akalilaaanjnafkdaddafhajhjhkaa...',
      '..akalilaianjnafjdaddajdajhjhkaa...',
      '..afalilaianjnafjdgddffeekhjhkaa...',
      '..afalilaianjnafjdgddgjeejhkhkaa...',
      '..afalilaianjnafjdgedgfeekhhaaha...',
      '..afalilaianjnafkdgddgfeeaaahaha...',
      '..afalilliiaaaaffhaddgjeeahahaha...',
      '...aalillahajchajhaddgaeeahchaa....',
      '....aailladakhkajdaddgaeeahaa......',
      '......aalahakhkajdaddgaeeaa........',
      '........aaaakhkakhaddgaaa..........',
      '............aakajdaddaa............',
      '..............aajdaaa..............',
      '................aa.................',
    ],
    [
      '........................ata........',
      '.......................atsta.......',
      '.......................asmsa.......',
      '........................faa........',
      '........................apa........',
      '........................apa........',
      '.......................aapa........',
      '.............aaaaaa...aqqma........',
      '......aaaaaarttttttaa.apma.........',
      '.aaaaasttttttttttttttaqma..........',
      '.akkkkotkkqttttttttttaqmaaa........',
      '..aahhkktokksjohhttttsmcattaa......',
      '..ahaajjkkhhdkkttttttsaasttttaa....',
      '..akahaachotkkkhhttttttttttttttaa..',
      '..akajhhaakckkkkkkkkotttsssssjffa..',
      '..akaajjhhaahhhtttttokkkjppaaaaa...',
      '..akhtaajjhhaadqsssjjjaaaaaacaca...',
      '..aklntjaaakjdaakkaaaaccahhahaha...',
      '..akalkqpanaajhaaaaccafcahhahaha...',
      '..akaaajjoanjakahaaddafcahhahkaa...',
      '..akaliaajanjncakdaddafcakhjhkaa...',
      '..akalilaaanjnafkdaddafhajhjhkaa...',
      '..akalilaianjnafjdaddajdajhjhkaa...',
      '..afalilaianjnafjdgddffeekhjhkaa...',
      '..afalilaianjnafjdgddgjeejhkhkaa...',
      '..afalilaianjnafjdgedgfeekhhaaha...',
      '..afalilaianjnafkdgedgfeeaaahaha...',
      '..afalilliiaaaaffhaddgjeeahahaha...',
      '...aalillahajccajhaddgaeeahchaa....',
      '....aailladakhkajdaddgaeeahaa......',
      '......aalahakhkajdaddgaeeaa........',
      '........aaaakhkakhaddgaaa..........',
      '............aakajdaddaa............',
      '..............aajdaaa..............',
      '................aa.................',
    ],
    [
      '...................................',
      '.........................a.........',
      '.......................atta........',
      '.......................atpsa.......',
      '.......................aqmpa.......',
      '........................aqa........',
      '.......................apma........',
      '.............aaaaaa....amm.........',
      '......aaaaaarttttttaa.aqma.........',
      '.aaaaastttttttttttttttapa..........',
      '.akkkkotkkqttttttttttaqmaaa........',
      '..aahhkktokksjohhttttamcsttaa......',
      '..ahaajjkkhhdkkttttttsaasttttaa....',
      '..akahaachotkkkhhttttttttttttttaa..',
      '..akajhhaakckkkkkkkkotttsssssjffa..',
      '..akaajjhhaahhhtttttokkkjppaaaaa...',
      '..akhtaajjhhaadqsssjjjaaaaaacaca...',
      '..aklntjaaakjdaakkaaaaccahhahaha...',
      '..akalkqpanaajhaaaaccafcahhahaha...',
      '..akaaajjoanjakahaaddafcahhahkaa...',
      '..akaliaajanjncakdaddafcakhjhkaa...',
      '..akalilaaanjnafkdaddaghajhkhkaa...',
      '..akalilaianjnafjdaddajcajhjhkaa...',
      '..afalilaianjnafjdgddffeekhjhkaa...',
      '..afalilaianjnafjdgddgjeekhjhkaa...',
      '..afalilaianjnafjdgedgfeekhhaaha...',
      '..afalilaianjnafkdgedgfeeaaahaha...',
      '..afalilliiaaaaffhaddgjeeahahaha...',
      '...aalillahajchajhaddgaeeahchaa....',
      '....aailladakhkajdaddgaeeahaa......',
      '......aalahakhkajdaddgaeeaa........',
      '........aaaakhkakdaddgaaa..........',
      '............aakajdaddaa............',
      '..............aajdaaa..............',
      '................aa.................',
    ],
    [
      '...................................',
      '........................baa........',
      '........................asta.......',
      '.......................atmsa.......',
      '.......................aqaa........',
      '........................apa........',
      '.......................aapa........',
      '.............aaaaaa...apqma........',
      '......aaaaaarttttttaa.aqm..........',
      '.aaaaastttttttttttttttama..........',
      '.akkkkotkkqttttttttttsmpaaa........',
      '..aahhkktokksjohhttttamcattaa......',
      '..ahaajjkkhhdkkttttttsaasttttaa....',
      '..akahaachotkkkhhttttttttttttttaa..',
      '..akajhhaakckkkkkkkkotttsssssjffa..',
      '..akaajjhhaahhhtttttokkkjppaaaaa...',
      '..akhtaajjhhaadqsssjjjaaaaaacaca...',
      '..aklntjaaakjdaakkaaaaccahhahaha...',
      '..akalkqpanaajdaaaaccafcahhahaha...',
      '..akaaajjoanjakahaaddafcahhahjaa...',
      '..akaliaajanjncakdaddafcakhjhkaa...',
      '..akalilaaanjnafjdaddafhajhkhkaa...',
      '..akalilaianjnafjdaddajcajhjhkaa...',
      '..afalilaianjnafjdgddffeekhjhkaa...',
      '..afalilaianjnafjdgddgjeejhjhkaa...',
      '..afalilaianjnafjdgedgfeekhhaaha...',
      '..afalilaianjnafkdgedgfeeaaahaha...',
      '..afalilliiaaaaffhaddgjeeahahaha...',
      '...aalillahajccajhaddgaeeahchaa....',
      '....aailladakhkajdaddgaeeahaa......',
      '......aalahakhkajdaddgaeeaa........',
      '........aaaakhkakdaddgaaa..........',
      '............aakajdaddaa............',
      '..............aajdaaa..............',
      '................aa.................',
    ],
    [
      '.........................a.........',
      '........................ata........',
      '.......................atsta.......',
      '.......................atmsa.......',
      '........................aaa........',
      '........................apa........',
      '........................apa........',
      '.............aaaaaa....aqma........',
      '......aaaaaarttttttaa.aqma.........',
      '.aaaaastttttttttttttttama..........',
      '.akkkkotkkqttttttttttaqmaaa........',
      '..aahhkktokksjohhttttsmcattaa......',
      '..ahaajjkkhhdkkttttttsaasttttaa....',
      '..akahaachotkkkhhttttttttttttttaa..',
      '..akajhhaakckkkkkkkkotttsssssjffa..',
      '..akaajjhhaahhhtttttokjkjppaaaaa...',
      '..akhtaajjhhaadqsssjjjaaaaaacaca...',
      '..aklntjaaakjdaakkaaaaccahhahaha...',
      '..akalkqpanaajhaaaaccafcahhahaha...',
      '..akaaajjoanjakahaaddafcahhahkaa...',
      '..akaliaajanjncakdaddafcakhjhkaa...',
      '..akalilaaanjnafjdaddafhajhkhkaa...',
      '..akalilaianjnafjdaddajcajhjhkaa...',
      '..afalilaianjnafjdgddffeekhjhkaa...',
      '..afalilaianjnafjdgddgjeekhjhkaa...',
      '..afalilaianjnafjdgedgfeekhhaaha...',
      '..afalilaianjnafkdgedgfeeaaahaha...',
      '..afalilliiaaaaffhaddgjeeahahaha...',
      '...aalillahajchajhaddgaeeahchaa....',
      '....aailladakhkajdaddgaeeahaa......',
      '......aalahakhkajdaddgaeeaa........',
      '........aaaakhkakdaddgaaa..........',
      '............aakajdaddaa............',
      '..............aajdaaa..............',
      '................aa.................',
    ],
    [
      '...................................',
      '........................ata........',
      '.......................atsa........',
      '.......................bsmsa.......',
      '........................aapa.......',
      '........................aqa........',
      '........................ama........',
      '.............aaaaaa....aam.........',
      '......aaaaaarttttttaa.apm..........',
      '.aaaaasttttttttttttttapma..........',
      '.akkkkotkkqttttttttttaqmsaa........',
      '..aahhkktokksjohhttttamcsttaa......',
      '..ahaajjkkhhdkkttttttsaasttttaa....',
      '..akahaachotkkkhhttttttttttttttaa..',
      '..akajhhaakckkkkkkkkotttsssssjffa..',
      '..akaajjhhaahhhtttttokkkjppaaaaa...',
      '..akhtaajjhhaadqsssjjjaaaaaacaca...',
      '..aklntjaaakjdaakkaaaaccahhahaha...',
      '..akalkqpanaajhaaaaccafcahhahaha...',
      '..akaaajjoanjakahaaddafcahhahkaa...',
      '..akaliaajanjncakdaddafcakhjhkaa...',
      '..akalilaaanjnafjdaddaghajhkhkaa...',
      '..akalilaianjnafjdaddajcajhjhkaa...',
      '..afalilaianjnafjdgddffeekhkhkaa...',
      '..afalilaianjnafjdgddgjeekhjhkaa...',
      '..afalilaianjnafjdgedgfeekhhaaha...',
      '..afalilaianjnafkdgedgfeeaaahaha...',
      '..afalilliiaaaaffhaddgjeeahahaha...',
      '...aalillahajchajhaddgaeeahchaa....',
      '....aailladakhkajdaddgaeeahaa......',
      '......aalahakhkajdaddgaeeaa........',
      '........aaaakhkakdaddgaaa..........',
      '............aakajdaddaa............',
      '..............aajdaaa..............',
      '................aa.................',
    ],
    [
      '.........................a.........',
      '........................ata........',
      '.......................amsta.......',
      '.......................asmsa.......',
      '........................aac........',
      '........................apa........',
      '........................cpa........',
      '.............aaaaaa....apm.........',
      '......aaaaaarttttttaa.aqma.........',
      '.aaaaasttttttttttttttapma..........',
      '.akkkkotkkqttttttttttaqmsaa........',
      '..aahhkktokksjohhttttamcsttaa......',
      '..ahaajjkkhhdkkttttttsaasttttaa....',
      '..akahaachotkkkhhttttttttttttttaa..',
      '..akajhhaakckkkkkkkkotttsssssjffa..',
      '..akaajjhhaahhhtttttokjjjppaaaaa...',
      '..akhtaajjhhaadqsssjjjaaaaaacaca...',
      '..aklntjaaakjdaakkaaaaccahhahaha...',
      '..akalkqpanaajhaaaaccafcahhahaha...',
      '..akaaajjoanjakahaaddafcahhahkaa...',
      '..akaliaajanjncakdaddafcakhjhkaa...',
      '..akalilaaanjnafjdaddafhajhkhkaa...',
      '..akalilaianjnafjdaddajdajhjhkaa...',
      '..afalilaianjnafjdgddffeekhkhkaa...',
      '..afalilaianjnafjdgddgjeekhjhkaa...',
      '..afalilaianjnafjdgedgfeekhhaaha...',
      '..afalilaianjnafkdgddgfeeaaahaha...',
      '..afalilliiaaaaffhaddgjeeahahaha...',
      '...aalillahajchajhaddgaeeahchaa....',
      '....aailladakhkajdaddgaeeahaa......',
      '......aalahakhkajdaddgaeeaa........',
      '........aaaakhkakhaddgaaa..........',
      '............aakajdaddaa............',
      '..............aajdaaa..............',
      '................aa.................',
    ],
    [
      '.........................a.........',
      '........................ata........',
      '.......................atsta.......',
      '.......................asmsa.......',
      '.......................apaa........',
      '........................apa........',
      '.......................aapa........',
      '.............aaaaaa....aqma........',
      '......aaaaaarttttttaa.aqma.........',
      '.aaaaastttttttttttttttama..........',
      '.akkkkotkkqttttttttttaqmaaa........',
      '..aahhkktokksjohhttttamcattaa......',
      '..ahaajjkkhhdkkttttttsaasttttaa....',
      '..akahaachotkkkhhttttttttttttttaa..',
      '..akajhhaakckkkkkkkkotttsssssjffa..',
      '..akaajjhhaahhhtttttokkkjppaaaaa...',
      '..akhtaajjhhaadqsssjjjaaaaaacaca...',
      '..aklntjaaakjdaakkaaaaccahhahaha...',
      '..akalkqpanaajdaaaaccafcahhahaha...',
      '..akaaajjoanjakahaaddafcahhahkaa...',
      '..akaliaajanjncakdaddafcakhjhkaa...',
      '..akalilaaanjnafjdaddafhajhkhkaa...',
      '..akalilaianjnafjdaddajcajhkhkaa...',
      '..afalilaianjnafjdgddffeekhkhkaa...',
      '..afalilaianjnafjdgddgjeekhjhkaa...',
      '..afalilaianjnafjdgddgfeekhhaaha...',
      '..afalilaianjnafkdgddgfeeaaahaha...',
      '..afalilliiaaaaffhaddgjeeahahaha...',
      '...aalilladajchajhaddgaeeahchaa....',
      '....aaillahakhkajhaddgaeeahaa......',
      '......aalahakhkakhaddgaeeaa........',
      '........aaaakhkajhaddgaaa..........',
      '............aakajhaddaa............',
      '..............aajdaaa..............',
      '................aa.................',
    ],
  ];

  Object.assign(SPRITES, {
    // 24 bend frames, not 2 variants: treeFrame() picks one off the wind wave.
    // They are drawn through `treeAtlas` below, never from this array - it is
    // kept because the atlas is built out of it and a single frame is handy.
    tree: treeSpr,
    // ONE texture for every pine on screen. A wide-open view holds a thousand
    // trees, and a drawImage whose source canvas differs from the last one
    // cannot be batched: on a GTX 1060 the sixteen separate canvases cost 97
    // fps against 199 for the same sprites drawn from a single source. So the
    // frames are laid out side by side and render() blits sub-rects of this.
    // FORTY-EIGHT columns: the second run of 24 is the first run mirrored, and
    // treeFrame() sends half the forest into it off the tile's hash. A
    // mirrored tree leans the other way, so the ladder runs backwards over
    // there and treeFrame() reverses the index when it crosses.
    // Each ROW is one palette (treePals above: three variants x three forest
    // depth tones, row = variant * 3 + tone), each holding the same 48 frames,
    // so the whole forest - every variant, every tone - is still one texture.
    // A cell index is column + row * cols (treeCell, js/draw/ground.js).
    // `fw`/`fh`/`cols` ride on the canvas so the caller needs no second constant.
    treeAtlas: (() => {
      const cols = treeSpr.length * 2;
      const fw = treeSpr[0].width, fh = treeSpr[0].height;
      const c = document.createElement('canvas');
      c.width = fw * cols; c.height = fh * treeRows.length;
      const g = c.getContext('2d');
      g.imageSmoothingEnabled = false;
      treeRows.forEach((row, r) => row.concat(row.map(flipH)).forEach((f, i) => g.drawImage(f, i * fw, r * fh)));
      c.fw = fw; c.fh = fh; c.cols = cols;
      return c;
    })(),
    stump: bake(stump, TPAL),
    goldOre: bake(goldOre, GOPAL),
    mine: bake(mine, MIPAL),
    bush: bake(bush, BPAL),
    bushEmpty: bake(bushEmpty, BPAL),
    bushBud: bake(bushBud, BPAL),
    bushRipen: bake(bushRipen, BPAL),
    deadTree: [bake(deadTree1, DTPAL), bake(deadTree2, DTPAL)],
    den: bake(den, DNPAL),
    hogHut: hogHut.map((f) => bake(f, HHPAL)),
  });
})();
