# Bakes the ROBOT scout skin into js/sprites/robot.js as char grids.
#
#   python3 app/bake-robot/bake.py     # needs numpy and pillow; rerun after changing the rig
#
# The robot is not typed by hand: rig.py paints him as flat-shaded facets on a
# 3D-jointed puppet (one tone per plane, which is the sharp look), projects him
# through the game's 35 degree camera, shrinks him to the game's pixel and
# bands him into the palette. He is drawn at twice a player's height, so these
# grids are the first 32 px character art in the game. The grids this writes
# are the game's only copy.
import os, numpy as np
from rig import render

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(HERE + '/../../js/sprites/robot.js')

SC = 0.62            # the rig is authored at 64 px; this stands him ~32 px tall
IDLE_N, RUN_N = 6, 4
# the game's four facings: right is seen a little from the front, so the lamp
# eyes stay on screen (a pure side view shrinks him to a pole); left is its mirror
FACINGS = {'down': 90, 'up': -90, 'right': 30}
CH = {'OUT': 'o', 'M1': '1', 'M2': '2', 'M3': '3', 'M4': '4', 'J1': 'j', 'J2': 'J',
      'GL': 'g', 'E1': 'a', 'E2': 'b', 'E3': 'c', 'TL': 'L', 'TM': 'T', 'TD': 't', 'TX': 'x'}
BASE = {'OUT': '#221a30', 'M1': '#eef2f8', 'M2': '#c3cad6', 'M3': '#949cae', 'M4': '#666e82',
        'J1': '#4a5264', 'J2': '#323846', 'GL': '#161a26', 'E1': '#fff4c2', 'E2': '#ffc94a', 'E3': '#e08a2a'}

clips = {d: {'idle': [render(h, 'idle', i / IDLE_N, SC)[0] for i in range(IDLE_N)],
             'run': [render(h, 'run', i / RUN_N, SC)[0] for i in range(RUN_N)]} for d, h in FACINGS.items()}
on = lambda f: np.array([[c is not None for c in row] for row in f])
alls = [f for c in clips.values() for fr in c.values() for f in fr]
m = np.any([on(f) for f in alls], axis=0)
ys, xs = np.nonzero(m)
# one box for every frame, centred on the body's root column so the mirror
# (left) keeps the feet where they were
from rig import OX
half = int(max(OX - xs.min(), xs.max() + 1 - OX))
x0, x1, y0, y1 = OX - half, OX + half, ys.min(), ys.max() + 1
iy, _ = np.nonzero(on(clips['down']['idle'][0]))
TOP = int(iy.min() - y0)       # empty rows over the standing head: the tells hang off the head
FOOT = int(iy.max() - y0)      # the row the soles stand on

def grid(f, box=None):
    a, b, c, d = box or (x0, x1, y0, y1)
    return [''.join('.' if f[y][x] is None else CH[f[y][x]] for x in range(a, b)) for y in range(c, d)]

# the skins screen's card: the rig at its full 64 px, standing at rest
icon = render(90, 'idle', 0, 1.0)[0]
iys, ixs = np.nonzero(on(icon))
ICON_BOX = (ixs.min(), ixs.max() + 1, iys.min(), iys.max() + 1)

out = ["'use strict';",
       "// The ROBOT scout skin (SCOUT_SKINS, js/ui/skins.js): a lean, faceted robot",
       "// with a screen face, lamp eyes and a team scarf, standing twice a player's",
       "// height. GENERATED by app/bake-robot/bake.py from a painted rig - edit the",
       "// rig and rebake, never these grids. Clips per facing: idle (breathing, one",
       "// blink) and run; left is the mirror of right. The chest and scarf are the",
       "// team paint (L/T/t/x: coatL, coat, coatD, fit), baked inside onTeams.",
       "(() => {",
       "  const { bakeClips, mapClips, flipH, onTeams, TEAM_SKINS } = SPR;",
       "  const BASE = { " + ', '.join(f"'{CH[k]}': '{v}'" for k, v in BASE.items()) + ", '.': null };",
       "  const GRIDS = {"]
for d, c in clips.items():
    out.append(f"    {d}: {{")
    for k, frames in c.items():
        out.append(f"      {k}: [")
        for f in frames:
            out.append("        [")
            out += [f"          '{r}'," for r in grid(f)]
            out.append("        ],")
        out.append("      ],")
    out.append("    },")
out += ["  };",
        "  // the card on the skins screen (skinArt, js/ui/skins.js): the full 64 px rig at rest",
        "  const ICON = ["]
out += [f"    '{r}'," for r in grid(icon, ICON_BOX)]
out += ["  ];",
        "  // TOP: the empty rows over the standing head; FOOT: the row the soles stand on",
        f"  const TOP = {TOP}, FOOT = {FOOT};",
        "  const sets = [];",
        "  onTeams(() => TEAM_SKINS.forEach((t, i) => {",
        "    const pal = Object.assign({}, BASE, { L: t.coatL, T: t.coat, t: t.coatD, x: t.fit });",
        "    const s = { down: bakeClips(GRIDS.down, pal), up: bakeClips(GRIDS.up, pal), right: bakeClips(GRIDS.right, pal) };",
        "    s.left = mapClips(s.right, flipH);",
        "    s.top = TOP; s.foot = FOOT; s.icon = SPR.bake(ICON, pal);",
        "    sets[i] = s;",
        "  }));",
        "  SPRITES.robotSkin = sets; // by skin(team)",
        "})();"]
open(OUT, 'w').write('\n'.join(out) + '\n')
print('wrote', OUT, 'frame', x1 - x0, 'x', y1 - y0, 'top', TOP, 'foot', FOOT)
