// Bakes the example bots in bots/*.js into js/bots/lib.js as source strings,
// so the game can list and run them with no server at all: opening index.html
// off the disk is a first-class way to run this game, and nothing may fetch.
//
//   node app/bake-bots.js    # rerun after editing or adding a file in bots/
//
// Each file becomes one BOT_LIB entry (botLibAdd, js/bots/api.js), its id the
// file's name. No packages.
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'bots');
const OUT = path.join(ROOT, 'js', 'bots', 'lib.js');

const files = fs.readdirSync(SRC).filter((f) => f.endsWith('.js')).sort();
let out = "'use strict';\n// ------------------------------------------------------------ bot library\n" +
  '// GENERATED by app/bake-bots.js from bots/*.js: never edit, rebake.\n' +
  '// The example bots, as source text the bot API runs (botLibAdd, js/bots/api.js).\n';
for (const f of files) {
  const src = fs.readFileSync(path.join(SRC, f), 'utf8');
  out += 'botLibAdd(' + JSON.stringify(f.replace(/\.js$/, '')) + ', ' + JSON.stringify(src) + ", 'inline');\n";
}
fs.writeFileSync(OUT, out);
console.log('baked ' + files.length + ' bots into ' + path.relative(ROOT, OUT));
