# Bakes the factory (the objective each company defends) into
# js/sprites/factory.js as char grids.
#
#   python3 app/bake-factory/bake.py     # needs numpy and Pillow
#
# factory.py builds the building from flat plates and style.py draws them at
# 1 px per world px, so the grids are the game's own pixel. The side's two
# ramps (team banding, glow) come out as their own keys and are painted in
# the game from TEAM_SKINS, so the colour-blind palettes repaint them too.
import os, numpy as np
import style
from factory import furnace, ruin, palette, PAL, TEAM_KEYS

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(HERE + '/../../js/sprites/factory.js')
W, H, OX, OY = 96, 100, 48, 76   # the frame, and the footprint's centre inside it

def hexs(c): return '#%02x%02x%02x' % tuple(c)

def bake(parts):
    img = style.draw(parts, palette(), 'air', 0.0, 1.0, W, H, ox=OX, oy=OY)
    keys = {}
    for m, ks in TEAM_KEYS.items():
        for i, k in enumerate(ks): keys[palette()[m][i]] = k
    fixed = {}
    rows = []
    for y in range(H):
        r = ''
        for x in range(W):
            if img[y, x, 3] == 0: r += '.'; continue
            c = tuple(int(v) for v in img[y, x, :3])
            if c in keys: r += keys[c]; continue
            if c not in fixed: fixed[c] = 'abcdefghijklmnopqrstuvwxyz0123456789'[len(fixed)]
            r += fixed[c]
        rows.append(r)
    return rows, fixed

def trim(sets):
    """drops the blank rows and columns every frame shares, keeping the origin"""
    top = min(next(i for i, r in enumerate(g) if r.strip('.')) for g in sets)
    bot = max(max(i for i, r in enumerate(g) if r.strip('.')) for g in sets)
    left = min(min(len(r) - len(r.lstrip('.')) for r in g if r.strip('.')) for g in sets)
    right = max(max(len(r.rstrip('.')) for r in g if r.strip('.')) for g in sets)
    return [[r[left:right] for r in g[top:bot + 1]] for g in sets], OX - left, OY - top

full, fa = bake(furnace())
fallen, fb = bake(ruin())
# one palette for both: remap the ruin's fixed keys onto the furnace's
pal = dict(fa)
for c in fb:
    if c not in pal: pal[c] = 'abcdefghijklmnopqrstuvwxyz0123456789'[len(pal)]
remap = {k: pal[c] for c, k in fb.items()}
fallen = [''.join(remap.get(ch, ch) for ch in r) for r in fallen]
(full, fallen), ox, oy = trim([full, fallen])

def js_grid(g): return '[\n' + ''.join("    '%s',\n" % r for r in g) + '  ]'
lines = ', '.join("'%s': '%s'" % (k, hexs(c)) for c, k in sorted(pal.items(), key=lambda kv: kv[1]))
src = f"""'use strict';
// The FACTORY each company defends: the whole building and its fallen ruin.
// GENERATED by app/bake-factory/bake.py (concept A, the furnace - a
// placeholder until the final art is picked); edit factory.py and rebake,
// never these grids. A-D paint the side's banding (fit, coatD, coat, coatL)
// and E-H its glow (coatD, mark, glow, trim) from TEAM_SKINS, so every
// colour-blind palette repaints it. FACTORY_OX/FACTORY_OY is the footprint's
// centre inside the frame: the world point drawFactory (js/boot.js) stands it on.
const FACTORY_OX = {ox}, FACTORY_OY = {oy};
(() => {{
  const {{ bake, TEAM_SKINS }} = SPR;
  const FACTORY_PAL = {{ '.': null, {lines} }};
  const FULL = {js_grid(full)};
  const FALLEN = {js_grid(fallen)};
  const teamPal = (t) => Object.assign({{}}, FACTORY_PAL, {{
    A: t.fit, B: t.coatD, C: t.coat, D: t.coatL, E: t.coatD, F: t.mark, G: t.glow, H: t.trim,
  }});
  // the hit flash: the standing building all white
  const FLASH = Object.keys(teamPal(TEAM_SKINS[0])).reduce((o, k) => (o[k] = k === '.' ? null : '#f4f7ff', o), {{}});
  const factory = [], factoryFallen = [];
  SPR.onTeams(() => TEAM_SKINS.forEach((t, i) => {{
    factory[i] = bake(FULL, teamPal(t));
    factoryFallen[i] = bake(FALLEN, teamPal(t));
  }}));
  Object.assign(SPRITES, {{
    factory,       // factory[team]: the standing building in that side's paint
    factoryFallen, // ...and what is left of it
    factoryFlash: bake(FULL, FLASH),
  }});
}})();
"""
open(OUT, 'w').write(src)
print('wrote', OUT, len(full[0]), 'x', len(full), 'origin', ox, oy, 'colours', len(pal))
