// Bakes the meadow snowdrops into js/sprites/snowdrops.js.
//
//   node app/bake-snowdrops/bake.js
//
// The art is painted by the Winter flowers work (a 2D cutout painter in
// Python, /mnt/project-files/winter-flowers/meadow16/ - its README has the
// rebuild): two transparent PNG atlases of 16x16 cells, copied in beside this
// file. snowdrop16-atlas.png is 4 variant rows x 3 states (closed, open,
// picked); snowdrop16-sway-atlas.png is the same 4 rows x 6 (closed leaning
// -1, 0, +1, then open leaning -1, 0, +1). This turns both into char grids
// and one palette, so the game bakes them at load like every other sprite
// and nothing is ever fetched. Never hand-edit the output: repaint, copy the
// PNGs in again and rebake. No packages: the PNGs are read with zlib.
'use strict';
const fs = require('fs');
const path = require('path');
const zlib = require('zlib');

const HERE = __dirname;
const OUT = path.join(HERE, '..', '..', 'js', 'sprites', 'snowdrops.js');
const CELL = 16;
const CHARS = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';

// a non-interlaced 8-bit RGBA PNG into { w, h, px: Uint8Array rgba }
function readPng(file) {
  const buf = fs.readFileSync(file);
  let o = 8, w = 0, h = 0;
  const idat = [];
  while (o < buf.length) {
    const len = buf.readUInt32BE(o), type = buf.toString('ascii', o + 4, o + 8);
    const data = buf.subarray(o + 8, o + 8 + len);
    if (type === 'IHDR') {
      w = data.readUInt32BE(0); h = data.readUInt32BE(4);
      if (data[8] !== 8 || data[9] !== 6 || data[12] !== 0) throw new Error(file + ': want 8-bit RGBA, non-interlaced');
    } else if (type === 'IDAT') idat.push(data);
    o += 12 + len;
  }
  const raw = zlib.inflateSync(Buffer.concat(idat)), px = new Uint8Array(w * h * 4), bpp = 4, stride = w * bpp;
  for (let y = 0; y < h; y++) {
    const f = raw[y * (stride + 1)], row = raw.subarray(y * (stride + 1) + 1, (y + 1) * (stride + 1));
    for (let x = 0; x < stride; x++) {
      const a = x >= bpp ? px[y * stride + x - bpp] : 0, b = y ? px[(y - 1) * stride + x] : 0;
      const c = x >= bpp && y ? px[(y - 1) * stride + x - bpp] : 0;
      let v = row[x];
      if (f === 1) v += a;
      else if (f === 2) v += b;
      else if (f === 3) v += (a + b) >> 1;
      else if (f === 4) { const p = a + b - c, pa = Math.abs(p - a), pb = Math.abs(p - b), pc = Math.abs(p - c); v += pa <= pb && pa <= pc ? a : pb <= pc ? b : c; }
      px[y * stride + x] = v & 255;
    }
  }
  return { w, h, px };
}

const pal = new Map(); // '#rrggbb' -> char
function charOf(r, g, b) {
  const hex = '#' + [r, g, b].map((v) => v.toString(16).padStart(2, '0')).join('');
  if (!pal.has(hex)) {
    if (pal.size >= CHARS.length) throw new Error('too many colours');
    pal.set(hex, CHARS[pal.size]);
  }
  return pal.get(hex);
}
// one cell of an atlas as grid rows; a pixel under half alpha is clear
function cell(img, col, row) {
  const out = [];
  for (let y = 0; y < CELL; y++) {
    let s = '';
    for (let x = 0; x < CELL; x++) {
      const i = ((row * CELL + y) * img.w + col * CELL + x) * 4;
      s += img.px[i + 3] < 128 ? '.' : charOf(img.px[i], img.px[i + 1], img.px[i + 2]);
    }
    out.push(s);
  }
  return out;
}

const still = readPng(path.join(HERE, 'snowdrop16-atlas.png'));
const sway = readPng(path.join(HERE, 'snowdrop16-sway-atlas.png'));
const rows = still.h / CELL;
const variants = [];
for (let v = 0; v < rows; v++) {
  variants.push({
    closed: [cell(sway, 0, v), cell(sway, 1, v), cell(sway, 2, v)],
    open: [cell(sway, 3, v), cell(sway, 4, v), cell(sway, 5, v)],
    picked: [cell(still, 2, v)],
  });
}

const grid = (g, pad) => '[\n' + g.map((r) => pad + "  '" + r + "',").join('\n') + '\n' + pad + ']';
let src = `'use strict';
// The meadow snowdrops (OBJECTS.snowdrop, js/world.js): SPRITES.snowdrop[variant]
// = { closed: [lean -1, 0, +1], open: [lean -1, 0, +1], picked: [one frame] },
// 16x16 cells with the feet at (8, 15). GENERATED by app/bake-snowdrops/bake.js
// from the Winter flowers painter's atlases - repaint and rebake, never edit
// these grids. CLOSED is the shut bud, OPEN the dawn bloom with its gold glint,
// PICKED the leaves and a snapped stem.
(() => {
  const { bake } = SPR;
  const PAL = { ${[...pal].map(([hex, c]) => `'${c}': '${hex}'`).join(', ')}, '.': null };
  const V = [
`;
for (const v of variants) {
  src += '    {\n';
  for (const k of ['closed', 'open', 'picked']) {
    src += `      ${k}: [\n` + v[k].map((g) => '        ' + grid(g, '        ') + ',').join('\n') + '\n      ],\n';
  }
  src += '    },\n';
}
src += `  ];
  SPRITES.snowdrop = V.map((v) => ({
    closed: v.closed.map((g) => bake(g, PAL)),
    open: v.open.map((g) => bake(g, PAL)),
    picked: v.picked.map((g) => bake(g, PAL)),
  }));
})();
`;
fs.writeFileSync(OUT, src);
console.log('wrote', path.relative(process.cwd(), OUT), variants.length, 'variants,', pal.size, 'colours');
