# Bakes the players' run and dodge roll into js/sprites/motion.js as char grids.
#
#   python app/bake-player/bake.py     # needs numpy; rerun after changing the doll
#   python app/bake-player/preview.py out.png     # every frame on one sheet, to judge first
#
# The frames are not typed by hand: doll.py paints each class body (bodies.py) as soft parts
# on a jointed doll, poses it (anim.py), turns it through the game's camera for each facing,
# shrinks it to the game's pixel and bands it into the class palette's letters. The idle and
# every other pose stay the hand-drawn grids in js/sprites/characters.js, which bakes these
# beside them in every team and look paint. The grids this writes are the game's only copy.
import os, sys
import numpy as np
from doll import OX, OY, GROUND, grounded
from bodies import BODIES
import anim

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(HERE + '/../../js/sprites/motion.js')
FACINGS = {'down': 90, 'up': -90, 'right': 0}           # left is right's mirror, in the game
UPRIGHT = {'run': lambda i: True, 'hold': lambda i: True, 'roll': lambda i: i in (0, len(anim.roll_poses('side')) - 2, len(anim.roll_poses('side')) - 1)}

_raw = {}


def raw(cls, kind, d):
    """the frames on the 24 x 24 work canvas, the body's root at (OX, OY)"""
    k = (cls, kind, d)
    if k in _raw: return _raw[k]
    body = BODIES[cls]; view = 'side' if d == 'right' else 'front'; h = FACINGS[d]
    if kind in ('run', 'hold'):
        pose = anim.run if kind == 'run' else anim.hold
        out = [body.render(pose(i, view), h) for i in range(anim.RUN_N)]
    else:
        out = []
        poses = anim.roll_poses(view)
        for i, (what, v) in enumerate(poses):
            if what == 'ball':
                g = body.render_ball(v, h)
            else:
                # the last, nearly standing frame is inked like the standing body (sides only);
                # the crouch, the dive and the deep squat like the compact roll shapes
                g = body.render(v, h, 'sides' if i == len(poses) - 1 else 'full')
            out.append(grounded(g))
    _raw[k] = out
    return out


# one box for every frame of both classes, centred on the body's column so the mirrored left
# frames keep the feet where they were; CELL_X/CELL_Y is where the 16 x 16 cell's top-left
# sits inside it, which is how drawPlayer lines a frame up with the body
KINDS = ('run', 'hold', 'roll')
_all = [g for c in BODIES for kd in KINDS for d in FACINGS for g in raw(c, kd, d)]
_on = np.array([[[ch != '.' for ch in row] for row in g] for g in _all]).any(0)
_ys, _xs = np.nonzero(_on)
_half = int(max(OX - _xs.min(), _xs.max() + 1 - OX))
X0, X1, Y0, Y1 = int(OX) - _half, int(OX) + _half, int(_ys.min()), int(_ys.max()) + 1
CELL_X, CELL_Y = int(OX) - 8 - X0, int(OY) - 16 - Y0


def frames(cls, kind, d):
    return [[r[X0:X1] for r in g[Y0:Y1]] for g in raw(cls, kind, d)]


def fringe(g, side):
    """where a character's fringe goes on this frame: [row, first column, first slot, count,
    second row too]. Like fringed() in characters.js: the first face row's skin under the hat
    takes the hair mask, slot by slot - head-on centred in the mask's six slots, side-on
    against its front end - and head-on the row under it takes the mask's second row."""
    for y, row in enumerate(g):
        xs = [x for x, c in enumerate(row) if c == 'k']
        if not xs: continue
        x0, x1 = xs[0], xs[-1]
        n = x1 - x0 + 1
        slot = 6 - n if side else (6 - n) // 2
        return [y, x0, slot, n, 0 if side else 1]
    return None


def js_rows(g, ind):
    return [f"{ind}'{r}'," for r in g]


def main():
    lines = ["'use strict';",
             "// The players' run cycle and dodge roll, both classes, three facings (left is the",
             "// mirror of right). GENERATED by app/bake-player/bake.py from a painted doll of each",
             "// class body - edit the doll and rebake, never these grids. Letters are the class",
             "// palette's (js/sprites/characters.js bakes them in every team and look paint).",
             "// RUN: eight frames, two steps, the right foot striking first. HOLD: the same legs with",
             "// the hands held in front (a drawn bow, a meal, a cast). ROLL: a crouch, a dive, the",
             "// tucked ball turning over once in 30 degree steps, a squat and a rise.",
             "(() => {",
             f"  // every frame is {X1 - X0} x {Y1 - Y0}; the 16 x 16 cell's top-left sits at (x, y) inside it",
             f"  const BOX = {{ w: {X1 - X0}, h: {Y1 - Y0}, x: {CELL_X}, y: {CELL_Y} }};",
             "  const GRIDS = {"]
    fr = {}
    for cls in BODIES:
        lines.append(f"    {cls}: {{")
        fr[cls] = {}
        for kind in KINDS:
            lines.append(f"      {kind}: {{")
            fr[cls][kind] = {}
            for d in FACINGS:
                lines.append(f"        {d}: [")
                fl = []
                for i, g in enumerate(frames(cls, kind, d)):
                    lines.append("          [")
                    lines += js_rows(g, '            ')
                    lines.append("          ],")
                    fl.append(fringe(g, d == 'right') if d != 'up' and UPRIGHT[kind](i) else None)
                fr[cls][kind][d] = fl
                lines.append("        ],")
            lines.append("      },")
        lines.append("    },")
    lines.append("  };")
    lines.append("  // an upright frame's first face row, for a character's fringe: [row, first column,")
    lines.append("  // first slot of the six-slot hair mask, count, and whether the row under it takes the")
    lines.append("  // mask's second row]; null where no face shows")
    lines.append("  const FRINGE = {")
    for cls in fr:
        lines.append(f"    {cls}: {{")
        for kind in fr[cls]:
            parts = ', '.join(f"{d}: [{', '.join('null' if f is None else '[' + ', '.join(map(str, f)) + ']' for f in fl)}]"
                              for d, fl in fr[cls][kind].items() if d != 'up')
            lines.append(f"      {kind}: {{ {parts} }},")
        lines.append("    },")
    lines.append("  };")
    bob = ', '.join(str(b) for b in anim.BOB)
    starts = ', '.join(f'{s:.3f}'.rstrip('0').rstrip('.') if s else '0' for s in anim.roll_starts())
    hbob = ', '.join(str(b) for b in anim.HOLD_BOB)
    lines.append(f"  // the body's bob per frame of the run and of the held run, whole px up, for what rides")
    lines.append(f"  // the body (the held tool, the gear marks); and the share of DODGE_T at which each roll")
    lines.append(f"  // frame starts")
    lines.append(f"  SPR.motion = {{ BOX, GRIDS, FRINGE, RUN_BOB: [{bob}], HOLD_BOB: [{hbob}], ROLL_AT: [{starts}] }};")
    lines.append("})();")
    open(OUT, 'w', newline='\n').write('\n'.join(lines) + '\n')
    low = [(c, k, d, i) for c in BODIES for k in KINDS for d in FACINGS
           for i, g in enumerate(raw(c, k, d)) if max(y for y, r in enumerate(g) if r.strip('.')) > GROUND]
    print('wrote', OUT, 'frame', X1 - X0, 'x', Y1 - Y0, 'cell at', (CELL_X, CELL_Y),
          '| below the ground row:', low or 'none')


if __name__ == '__main__':
    main()
